### ISSUE TITLE
tfe_workspace_variable_set incorrect documentation

### ISSUE THREAD

**Issue by ADunn-Insight** [hashicorp/terraform-provider-tfe#1007]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
1.3.9
```

#### Terraform Configuration Files

```terraform
terraform {
  required_version = "~> 1.3.0"
  required_providers {
    tfe = {
      source  = "registry.terraform.io/hashicorp/tfe"
      version = "~> 0.40.0"
    }
  }
}
```

#### Debug Output

```plaintext
"my var set" and "my workspace" are generic for sensitive information
│ Error: Error applying variable set id my var set to workspace my workspace: invalid variable set ID
│ 
│   with tfe_workspace_variable_set.var_set["example"],
│   on main.tf line 12, in resource "tfe_workspace_variable_set" "var_set":
│   12: resource "tfe_workspace_variable_set" "var_set" {
│ 
```

#### Expected Behavior

[The documentation](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace_variable_set) states the variable_set_id is "Name of the variable set to add". I provided the name of the variable set found in TFC and that should have been correctly assigned.
#### Actual Behavior

I received an error that terraform could not find the variable set via the name provided.
#### Additional Context

I tested the resource by using a data lookup for the variable set and then passed in the variable set ID that was found via the data call. 
```terraform
data "tfe_variable_set" "var_set" {
  name         = "var set name"
  organization = "my org"
}
...
resource "tfe_workspace_variable_set" "var_set" {
  workspace_id    = tfe_workspace_workspaces.id
  variable_set_id = data.tfe_variable_set.var_set.id
}
```
When I provided that ID, terraform was able to find that variable set because the ID is different than the name of the variable set. 
The data.tfe_variable_set.var_set.id was "varset-lettersandnumbers" which is of course different than the name I gave to my variable set. 
Therefore, the documentation provides incorrect information regarding how to reference the variable set to be assigned to the workspace. 
A solution to this problem would be to either update the documentation to specify that the resource requires the ID of the variable set and not the name, or update the resource to have a property "variable_set_name" that allows the user to specify via the name and not the ID.

**Comment by sebasslash** [comment]
Thanks for reporting this and apologies for the confusion.  You are correct, what you need to provide is the external ID for the variable set: `varset-XXXXXXX`. For future reference, any time you see `ID` referenced in the docs, it means the resource's ID. The resource ID always follows: `<resource-prefix>-XXXXXXX` format and can always be referenced using `some_tfe_resource.some_name.id`. The only exception to this is `tfe_organization`, where you can use `tfe_organization.my_organization.name` or `tfe_organization.my_organization.id` interchangeably. 

I will update the docs.
