### ISSUE TITLE
Incorrect tfe_team_project_access docs

### ISSUE THREAD

**Issue by sfc-gh-ngaberel** [hashicorp/terraform-provider-tfe#1008]
The [tfe_team_project_access resource docs page](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/team_project_access) lists the `sentinel-mocks`, `state-versions` and `run-tasks` properties as using dashes for word separation but `terraform validate` actually wants underscores.
![image](https://github.com/hashicorp/terraform-provider-tfe/assets/128428373/35be6213-6577-4932-adbf-8d6e5ebab713)

#### Terraform Cloud/Enterprise version

TFE v202308-1 (probably not relevant)

#### Terraform version

Terraform 1.0.0

#### Terraform Configuration Files
*not relevant*

#### Debug Output

```plaintext
...
```

**Comment by sebasslash** [comment]
Confirmed. Will update docs.

**Comment by sebasslash** [comment]
Thanks for reporting this issue! 🚀
