### ISSUE TITLE
Library for Centralization Of Variables

### ISSUE THREAD

**Issue by sheldonhull** [hashicorp/terraform-provider-tfe#104]
## The Problem

Azure Devops has the concept of linking variables from a variable group. Additionally, it can be a secure file. Both of these can be linked to jobs, and this results in the credentials for all being able to be changed by updating the library credential, instead of having to put environment variables in every single job. 

Right now, managing many workspaces requires a lot of effort with the provider as the credentials have to be embedded. This results in more change and risk in breaking things when you have many jobs requiring credential rotation

## Possible Suggestions

Consider shared variables that can be linked, and then automatically available in child tasks, or some type of service connections that be leveraged.

**Comment by barrettclark** [comment]
Closing. We have implemented variable sets in TFC.
