### ISSUE TITLE
Terraform 1.6.0 breaks "tfe_outputs" data source

### ISSUE THREAD

**Issue by vbyrd** [hashicorp/terraform-provider-tfe#1088]
#### Terraform Cloud/Enterprise version
```plaintext
Terraform Cloud
```

#### Terraform version
```plaintext
Terraform Version: 1.6.0
```

#### Terraform Configuration Files
```terraform
provider "tfe" {
  token = "mytoken"
}

data "tfe_outputs" "example" {
  organization = "someorg"
  workspace    = "someworkspace"
}
```

#### Debug Output
```plaintext
N/A
```

#### Expected Behavior
Data source should work as expected

#### Actual Behavior
```bash
Error: Data Source Not Implemented

  with data.tfe_outputs.example,
  on data-sources.tf line 1, in data "tfe_outputs" "example":
   1: data "tfe_outputs" "example" {
```

#### Additional Context
N/A

**Comment by nfagerlund** [comment]
Wow, that's exciting! 

I have some idea of where to start looking, and hopefully it'll be an easy fix... fingers crossed. Thank you for reporting this!

**Comment by priestjim** [comment]
From a cursory search, it looks like its definition is missing from https://github.com/hashicorp/terraform-provider-tfe/blob/main/internal/provider/provider.go#L111

**Comment by nfagerlund** [comment]
The upshot: terraform-provider-tfe is actually a muxed provider that is implemented by THREE separate provider servers under the hood. One of them provides ONLY the tfe_outputs data source. That one had a misconfigured setup function that is only called by terraform 1.6+. 

As we hoped, implementing the expected return value for that function seems to fix the problem.
