### ISSUE TITLE
Add an "or_create" flag to the TFE_WORKSPACE resource.

### ISSUE THREAD

**Issue by tnc-tschmidt** [hashicorp/terraform-provider-tfe#1099]
#### Use-cases
My specific use case is that I need to create a large number of resources acros an AWS organization, enough that it is impossible to run it via pipelines or actions as it greatly exceeds memory available.

To that end, I'd like to automate breaking this out into multiple modules and run them individually. As we use Terraform cloud for state storage, I'd like to use separate TF Cloud workspaces, created programtically as well.

#### Attempted Solutions
The terraform workspace select command supports a flag of -or-create which will create the workspace if it doesn't exist and believe this should be an option for the TFE cloud provider.

There are other more complex solutions but would prefer to keep this as close to base terraform code as possible.

#### Proposal
Simply add or_create = "true" to the tfe_workspace resource.

**Comment by barrettclark** [comment]
If you're using Terraform Cloud, `terraform init` will create the workspace in TFC. `terraform workspace select` isn't applicable to TFC workspaces.

Using terraform-provider-tfe, the tfe_workspace resource will create the workspace if it is not represented in state. If the workspace _does_ exist and is not represented in state then you'd need to import it to allow it to be represented in state.

Having said all that, can you help me understand what problem you're running into? I am not clear on how the creation of a workspace factors into memory bloat from creating too many AWS resources.

**Comment by tnc-tschmidt** [comment]
I do see TF 1.6 now supports projects but the docs don't seem to mention creation except obliquley. TF returns a 404 when I specify a workspace that doesn't exist.

As far as use case, it's just that if I create a lot of modules and resources, terraform ends up using ~15.8GB of memory so I would like to break those out into separate modules with a workspace for each.

```
terraform {
  cloud {
    organization = "ME"

    workspaces {
      project = "MP"
      name = "DEV"
    }
  }
  required_providers {
    tfe = {
      version = "~> 0.49.2"
    }
  }
}
```

```
$ terraform -version
Terraform v1.6.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.49.2


$ terraform apply

│ Error: error starting operation: workspace DEV not found
│ 
│ For security, Terraform Cloud returns '404 Not Found' responses for resources
│ for resources that a user doesn't have access to, in addition to resources that
│ do not exist. If the resource does exist, please check the permissions of the provided token.
```
https://developer.hashicorp.com/terraform/cli/cloud/settings
Under workspaces->tags is the only place mentioning creation, but unfortunately it also says to use the cli command which isn;t supported.

**Comment by barrettclark** [comment]
You have to run `terraform init` before you can run `terraform apply`. If you make any changes in the cloud stanza you'll need to re-init as well.

**Comment by tnc-tschmidt** [comment]
Argh, yep, that worked (normally TF would error if I had forgotten the init).

Thanks, that gets me where I need to be to break this out. I will close this issue out. 

Open to any suggestions as for a better way to do this. Essentially I am dynmically creating a list or resources for a number of different cloud accounts. I have already gotten creative with auto generating a list of the modules with roles to assume, etc. You could argue something like cloudformation stacksets would be better for this, but then I would have to use cloudformation :-).

**Comment by barrettclark** [comment]
Are you executing the plan and apply in Terraform Cloud and getting the memory bloat there, or are you being throttled in GitHub Actions?

If you're not using TFC to execute the apply I'd start there. Each workspace has it's own state representation, so I don't think you're getting memory bloat from loading too many resources across too many workspaces. If a given workspace has a _lot_ of resources, though, there wouldn't be any getting around how much space it takes to represent that in state -- regardless of whether things are broken into separate modules.

**Comment by tnc-tschmidt** [comment]
Actually BitBUcket pipelines. For TFC, I can't find specific docs on mempry requirements, but since the state currently has 2966 objects and is 4.5M in size and expected to grow, it only makes sense to break it up now. Being able to dynamically create the workspace was the only "deal breaker" for me to run the modules separately and still utilize the TFC for state storage.
