### ISSUE TITLE
[Feature Request] support the credentials_helper for TFE creds.

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/terraform-provider-tfe#111]
Hi, It would be great if the provider was able to source the TFE token via the same mechanisms that Terraform can use, specifically the **credentials_helper** in your _.terraformrc_ file. This would help when testing local-apply and remote-state-only Terraform runs.

An example of how to setup a credential helper is linked in this Gist

[Terraform Credential Helper Gist](https://gist.github.com/tristanmorgan/ac541f5689272a34e6135977c2bdf8ad)

**Comment by tristanmorgan** [comment]
Adding link to Terraform docs [Credentials Helpers](https://www.terraform.io/docs/internals/credentials-helpers.html)

**Comment by chrisarcand** [comment]
Duplicate of #102, essentially

**Comment by tristanmorgan** [comment]
> Duplicate of #102, essentially

I would agree about it being a duplicate if the solution to #102 includes the use of a credential provider and not just documentation about currently implemented features.

**Comment by tristanmorgan** [comment]
Closing for now.
