### ISSUE TITLE
tfe_workspace_run failed to apply on resource not found error

### ISSUE THREAD

**Issue by sereinity** [hashicorp/terraform-provider-tfe#1150]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
Terraform v1.6.4
+ provider registry.terraform.io/hashicorp/tfe v0.50.0
```

#### Terraform Configuration Files

```terraform
resource "tfe_workspace" "settings" {
  name                   = var.workspace_name
  organization           = "my-org"
  project_id             = var.tfc_project_id
  tag_names              = ["some", "tags"]
  allow_destroy_plan     = false
  force_delete           = true
  auto_apply             = false
  auto_apply_run_trigger = true
  execution_mode         = "remote"
  queue_all_runs         = false
  trigger_patterns = [
    "clusters/preprod/terraform-setup-env/**/*",
  ]
  working_directory = "clusters/preprod/terraform-setup-env"
  vcs_repo {
    identifier     = "my-gitlab/repo"
    branch         = var.vcs_branch
    oauth_token_id = var.vcs_token_id
  }
}

resource "tfe_variable" "var1" {
  key          = "var1"
  value        = "xxx"
  category     = "terraform"
  workspace_id = tfe_workspace.settings.id
}
# And many other tfe_variable blocks

resource "tfe_workspace_run" "settings" {
  workspace_id = tfe_workspace.settings.id
  apply {
    manual_confirm = false
    wait_for_run   = true
  }
}
```

#### Debug Output

(redacted)
```plaintext
[DEBUG] Read workspace by ID ws-xxxxxxxxxxxxxx
[DEBUG] provider.terraform-provider-tfe_v0.50.0_x5: [DEBUG] Create run for workspace: ws-xxxxxxxxxxxxxx
Error: error creating run for workspace ws-xxxxxxxxxxxxxx: resource not found
```

#### Expected Behavior
A run should have occurred, a meaningful error prompted if I misused the provider.

#### Actual Behavior

The apply fail. No run triggered.

#### Additional Context

The plan is also run from terraform cloud. Every resources exists except for the run, same behavior if I taint the workspace.

**Comment by barrettclark** [comment]
Thank you for the issue submission @sereinity. I was not able to reproduce this -- the run was created when I added a `tfe_workspace_run` resource. Do you have any more steps to reproduce that you can add?

**Comment by sereinity** [comment]
I will try to reproduce this with a more complete minimalist example.

**Comment by sereinity** [comment]
:exploding_head: I reproduced it, and I think I understand why it fails: the token I was using (organization token) was generated more than a year ago, I think that the token miss some permissions to trigger a pipeline.
