### ISSUE TITLE
Error: The terraform-provider-tfe_v0.52.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by cvasudeva** [hashicorp/terraform-provider-tfe#1280]
#### Terraform Cloud/Enterprise version
0.52.0
#### Terraform version
Terraform [v1.5.7]
#### Terraform Configuration Files
├── provider[registry.terraform.io/hashicorp/azurerm] 3.57.0
├── provider[registry.terraform.io/hashicorp/tfe] 0.52.0
#### Debug Output
https://gist.github.com/cvasudeva/57ddbfc11d38c0e92619222983544e36
#### Expected Behavior 
It should have created workspaces at terraform cloud and plan should have run successfully
#### Actual Behavior
It threw an error The terraform-provider-tfe_v0.52.0_x5 plugin crashed!
#### Additional Context
At first the error occurred for tfe 0.48.0 version later we downgraded it to 0.47.0 and changed to the latest version 0.52.0 we are getting plugin crashed error for all these version
![image](https://github.com/hashicorp/terraform-provider-tfe/assets/89589169/fe911077-9ba5-4496-8dfa-2a7139a8ab2d)

**Comment by barrettclark** [comment]
Additional context: It appears there is a run trigger that can be read and the target workspace is missing. Was the workspace deleted that should also have deleted the run trigger?

**Comment by cvasudeva** [comment]
Thanks Barrettclark manually removing run trigger in the dependent workspace helped.
