### ISSUE TITLE
tfe_policy does not actually alter enforce_mode on OPA policies

### ISSUE THREAD

**Issue by skeggse** [hashicorp/terraform-provider-tfe#1407]
#### Terraform Enterprise version

TFCB

#### Terraform version

```plaintext
Terraform v1.9.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.56.0
```

#### Terraform Configuration Files

```terraform
resource "tfe_policy" "policy" {
  organization = "..."
  description  = "My policy"
  # Set this to `advisory` during create, then try applying a new plan after changing it to `mandatory`.
  enforce_mode = "advisory"
  kind         = "opa"
  name         = "test_policy"
  query        = "data.whatever"
  policy       = "deny {\n  false\n}"
}
```

#### Debug Output

The salient output from the debug log seems to be the following:

```plaintext
2024-07-05T18:50:56.601-0700 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/tfe\"]" produced an unexpected new value for tfe_policy.policy, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .enforce_mode: was cty.StringVal("mandatory"), but now cty.StringVal("advisory")
```

I'll send a complete log in a support ticket.

#### Expected Behavior

The provider should configure the policy in `mandatory` enforcement mode.

#### Actual Behavior

The provider configures the policy in `advisory` enforcement mode.

#### Additional Context

I've tried this from our own Terraform Cloud agents, and tried running this locally. No dice.

**Comment by glennsarti** [comment]
@skeggse This will be fixed in the next release (v0.61.0)
