### ISSUE TITLE
Allow management of Organization Users

### ISSUE THREAD

**Issue by philbal611** [hashicorp/terraform-provider-tfe#145]
When adding a new User to an existing Team, we're getting an error that the user is not a member of the Organization. I'm not quite sure how this is meant to me managed...either in this provider, nor in the TFE UI.

```hcl
resource "tfe_organization" "org" {
  name                    = "Org"
  email                   = "${var.email}"
  session_timeout_minutes = "30"
}

resource "tfe_team" "team" {
  name         = "Team"
  organization = "${tfe_organization.org.name}"
}

resource "tfe_team_members" "team" {
  team_id = "${tfe_team.team.id}"

  usernames = [
    "existing_user_1",
    "existing_user_2",
    "new_user_1",
  ]
}
```

```hcl
* tfe_team_members.team: 1 error occurred:
* tfe_team_members.team: Error adding users to team team-3d2r12xWnKd47VNT: bad request

new_user_1 is not a member of the organization
bad request
```

This is different from the `new_user_1 does not exist` error, which occurs when the user has not performed an initial login (when using SAML at least).

TF Version: `0.11.14`
TFE Version: `v202002-1`

**Comment by philbal611** [comment]
After a bit of research & reaching out to Hashicorp Support, it appears that this is a new feature, and that The issue with the TFE UI is a bug, which will be resolved in a release of TFE version `v202002-2`.

I suppose that, instead of a bug fix report, this issue would then be a feature request to allow this functionality to be managed by the TFE provider.

**Comment by chrisarcand** [comment]
Closing; This was since added: [`tfe_organization_membership`](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/organization_membership)
