### ISSUE TITLE
tfe_workspace_run_task apply fails when using stages argument and TFE v202408-1

### ISSUE THREAD

**Issue by derhally** [hashicorp/terraform-provider-tfe#1456]
We are getting an error when using the new "stages' argument on the resource tfe_workspace_run_task.

```hcl

resource "tfe_workspace_run_task" "vm_agent" {
  task_id      = tfe_organization_run_task.default.id
  workspace_id = var.workspace_id
  stages = [
    "post_plan",
    "pre_plan",
  ]
  enforcement_level = "advisory"
}
```

#### Terraform Enterprise version
v202408-1

#### Terraform version

```plaintext
1.3.8
```

#### TFE Provider version
```plaintext
0.58.1
```

#### Debug Output

```plaintext
tfe_workspace_run_task.vm_agent, provider "provider[\\\"registry.terraform.io/hashicorp/tfe\\\"]" produced an unexpected new value: .stages: element 1 has vanished.\n\nThis is a bug in the provider, which should be reported in the provider's own issue tracker."},"type":"diagnostic"}
Operation failed: failed running terraform apply (exit 1)
```

#### Expected Behavior
Should have applied without errors

#### Actual Behavior
Error

```
When applying changes to tfe_workspace_run_task.vm_agent, provider "provider[\"registry.terraform.io/hashicorp/tfe\"]" produced an unexpected new value: .stages: element 1 has vanished.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by glennsarti** [comment]
@derhally Just to get some more context here...

Was this a new run task you were trying to create or updating a new one?

**Comment by derhally** [comment]
@glennsarti Sorry about that, the TFE provider is 0.58.1 and it was new resource that was setting tasks for workspaces.

**Comment by glennsarti** [comment]
Thanks @derhally

**Comment by glennsarti** [comment]
This'll be fixed in the next release

**Comment by evilensky** [comment]
Hello. We have an existing run task that we tried to update from `stage = "pre_plan"` to `stages = [ "pre_plan"]`, and the resulting plan tries to change all instances of this run_task into:

<img width="504" alt="image" src="https://github.com/user-attachments/assets/fd2fc783-19dd-41e8-9026-4832198787e8">

Is that this issue also?

**Comment by mikesmitty** [comment]
> This'll be fixed in the next release

Any word on when the next release will be?

**Comment by glennsarti** [comment]
@mikesmitty [v0.59.0](https://github.com/hashicorp/terraform-provider-tfe/releases/tag/v0.59.0) was released with the fix.
