### ISSUE TITLE
Failed to import existing workspace by ID or by org/ws 

### ISSUE THREAD

**Issue by Hellseher** [hashicorp/terraform-provider-tfe#1496]
Hi,

I've created team token, exported TFE_TOKEN in my current shell session and tried to import existing workspace into state.
My attempt was failed for ID and org/ws,

#### Terraform version

```plaintext
terraform -version
Terraform v1.9.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/tfe v0.57.1
```

#### Terraform Configuration Files

```terraform
resource "tfe_workspace" "this" {
  for_each = { for ws in local.deployments.workspaces : ws.name => ws }

  name = each.value.name

  allow_destroy_plan            = lookup(each.value, "allow_destroy_plan", false)
  auto_apply                    = lookup(each.value, "auto_apply", false)
  auto_apply_run_trigger        = lookup(each.value, "auto_apply", false)
  description                   = lookup(each.value, "description", "")
  file_triggers_enabled         = lookup(each.value, "file_triggers_enabled", true)
  force_delete                  = lookup(each.value, "force_delete", false)
  global_remote_state           = lookup(each.value, "global_remote_state", false)
  organization                  = lookup(each.value, "organization", tfe_organization.my_org.id)
  queue_all_runs                = lookup(each.value, "queue_all_runs", false)
  remote_state_consumer_ids     = lookup(each.value, "remote_state_consumer_ids", [])
  structured_run_output_enabled = lookup(each.value, "structured_run_output_enabled", false)
  terraform_version             = lookup(each.value, "terraform_version", var.terraform_version)
  working_directory             = lookup(each.value, "working_directory", "")
}

```

#### Debug Output

```plaintext
...
2024-10-17T16:43:08.902+0100 [WARN]  Provider "registry.terraform.io/hashicorp/tfe" produced an unexpected new value for tfe_workspace.this["my-workspace"] during refresh.
      - Root object was present, but now absent
2024-10-17T16:43:08.903+0100 [ERROR] vertex "import tfe_workspace.this[\"my-workspace\"] result" error: Cannot import non-existent remote object
2024-10-17T16:43:08.903+0100 [TRACE] vertex "import tfe_workspace.this[\"my-workspace\"] result": visit complete, with errors
2024-10-17T16:43:08.903+0100 [TRACE] dag/walk: upstream of "root" errored, so skipping
...
```

#### Expected Behavior

Exiting workspace is imported.

#### Actual Behavior

Exiting workspace is failed to be imported.

by ID
```
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "tfe_workspace.this[\"my-workspace\"]", the provider detected that no object exists with the given id. Only pre-existing objects can be imported;
│ check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
```

by org/ws

```
│ Error: error retrieving workspace with name my-workspace from organization my-org Error reading configuration of workspace my-org/my-workspace: resource not found
```

#### Additional Context

The error output would be misleading, e.g. if the current token does not have permission to do any sort of action it's no way to determine it at all.

**Comment by Hellseher** [comment]
I might hit this:

```
To manage the full selection of resources, provide a [user token](https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html) from an account with appropriate permissions. This user should belong to the "owners" team of every organization you wish to manage.
```
Why Team token may not be used to manage the resource?

**Comment by sebasslash** [comment]
To add some more context, team **write** access on a workspace can be granted in a few ways:
- The organization explicitly allows the team to manage **all** workspaces. If that is not the case then: 
- The project grants write access by providing write or full manage access to the project. Alternatively, workspace write access could also be granted by explicitly applying custom project permissions to the team and allowing DELETE access to the project's workspaces.
- If a project does not apply in this scenario, and/or no explicit workspace write access is granted by the organization or project, then write access must be directly set on the workspace for your particular team. In the UI, these settings can be found `Your Workspace Page > Workspace Settings > Team Access`. 

Without knowing more about how team access is set up across your organization, we can't really help troubleshoot the authorization issue. That said, please don't share those details here :sweat_smile: and open a support ticket if one of the access methods above is true for your team & you still don't have access. 

Thanks!
