### ISSUE TITLE
Unclear error when attempting to add teams to free accounts

### ISSUE THREAD

**Issue by tedivm** [hashicorp/terraform-provider-tfe#171]
If you attempt to add a team to a free account it gives an error about not being able to find the organization. This was easily resolved by upgrading the account, but it wasn't clear that that was the needed step

**Comment by koikonom** [comment]
Hi @tedivm ,

Unfortunately the messages are coming straight from TFC, we cannot really from the provider side if the error is caused because of an account limitation or because the organization is not really there.

**Comment by tedivm** [comment]
Isn't this project maintained by Hashicorp, the company that makes Terraform Cloud?

**Comment by koikonom** [comment]
Apologies, I should have elaborated. You are correct, this project is maintained by HashiCorp but there are different teams with different backlogs and roadmaps handling the two sides (one side being the provider and the other being the TFC platform). 

I have already created an internal issue for the TFC team to prioritize and address, but until the service API can send a more complete error message, there is no other way for the provider to detect this behavior and respond accordingly.

**Comment by magzim21** [comment]
`Error: Error creating team owners for organization <org>: missing entitlements to create teams`. 
Activating standard plan solved this.
