### ISSUE TITLE
Provider creates plans when authentication fails

### ISSUE THREAD

**Issue by tedivm** [hashicorp/terraform-provider-tfe#174]
Rather than failing, this provider silently ignores authentication plans and creates plans. Since it can't see the resources in the organization when refreshing state it instead attempts to recreate them.

**Comment by bendrucker** [comment]
What exactly is your auth failure? Terraform providers should not ignore rejected credentials, e.g. HTTP 401 and 403 errors. However, they do handle 404 errors by assuming the resource needs to be created. Sometimes errors you might expect as 403 are returned as 404s to avoid leaking resource names.

**Comment by tedivm** [comment]
In this case I forgot to put an authentication token at all. If there is no auth token I feel that the project should fail immediately, since it is impossible to write/create resources without write access (and you can't have write access without the auth token).

**Comment by bendrucker** [comment]
Yep, that sounds reasonable. How are you getting past this though?

https://github.com/terraform-providers/terraform-provider-tfe/blob/master/tfe/provider.go#L187

The provider `ConfigureFunc` should be erroring if no token is set

**Comment by tedivm** [comment]
I hadn't set a token at all but did not receive that error.

**Comment by bendrucker** [comment]
With a super minimal config:

```terraform
resource "tfe_team" "t" {
  name = "foo"
  organization = "bar"
}
```

I get:

```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: required token could not be found

  on <empty> line 0:
  (source code not available)
```

Turning on `TF_LOG=debug` could help pinpoint the behavior here. The provider should only be treating 404s as "expected." But as noted earlier, authentication errors (e.g. an invalid organization name) can manifest as 404s.

You could add a line logging the token and build the provider, that might give you a hint to what it's set to if just examining logs doesn't help.

**Comment by koikonom** [comment]
Hi @tedivm,  thanks for taking the time to report this issue!

If you are still having problems please share the debug log as well as an example config so we can better understand the issue.

**Comment by tedivm** [comment]
I found the bug and fixed it in my setup in May- I'm not sure what has happened since then or if it has been resolved.
