### ISSUE TITLE
Is there a way to grab the current workspace id

### ISSUE THREAD

**Issue by vibhuyadav** [hashicorp/terraform-provider-tfe#187]
Looking for a way to access the current workspace id while running the terraform plan. Currently it is some ws-* (some guid)

**Comment by bendrucker** [comment]
This is not available automatically. You'd have to create your workspaces with the provider and add it as a variable:

```tf
resource "tfe_workspace" "test" {
  name         = "my-workspace-name"
  organization = "my-org-name"
}

resource "tfe_variable" "test" {
  key          = "workspace_id"
  value        = tfe_workpace.test.id
  category     = "terraform"
  workspace_id = tfe_workpace.test.id
  description  = "a useful description"
}
```

**Comment by joakimhellum** [comment]
Hi, at least the workspace name should be available in Terraform Cloud environment using the `TFC_WORKSPACE_NAME` variable.
An idea could be to add new `tfe_current_run` data source in Terraform which would make these variables available?

Potential Terraform configuration for this could be:
```hcl
data "tfe_current_run" "test" {}

output "workspace_name" {
  value = data.tfe_current_run.workspace_name
}
```
Then you could use the `tfe_workspace` data source to get the workspace ID from the workspace name and organization.

References:
https://www.terraform.io/docs/cloud/run/run-environment.html

**Comment by chrisarcand** [comment]
As joakimhellum mentioned above, the workspace name is available to the run environment, meaning that the best way to snag the current workspace ID would be to use the workspace data source as follows:

```
variable "TFC_WORKSPACE_NAME" {
  type = string
}

data "tfe_workspace" "test" {
  name         = var.TFC_WORKSPACE_NAME
  organization = "my-org-name"
}
```

The organization name might not be as easily sourced and either hardcoded or within the same configuration as bendrucker did above with a workspace.
