### ISSUE TITLE
feature request: trigger plan/apply on tfe_variable changes

### ISSUE THREAD

**Issue by 3h4x** [hashicorp/terraform-provider-tfe#193]
Hey
We use a lot of `tfe` for dynamic workspace provisioning. Configuration is partially in `terraform-cloud` like sensitve variables or global variables. For us every change in variables should trigger plan as it's module configuration, VCS is not enough.

It would be nice to have a flag parameter like `trigger_plan_on_change` which when set to `true` would trigger plan.

**Comment by chrisarcand** [comment]
If I understand correctly, what you're asking for is a feature to the Terraform Cloud platform and not to this provider, so I'm not sure there's anything actionable here for now.

I did think of an alternative you may want to explore, though given that you said you dynamically provision workspaces as part of your workflow perhaps you mean you already do this and it's not enough. Using [Run Triggers](https://www.terraform.io/docs/cloud/workspaces/run-triggers.html), you could provision all of your workspace variables in workspace which then has triggers set on all workspace whose variables you've just provisioned. Thus, any time a variable is changed via this configuration - which hopefully is your single source of truth for how you edit your variables - a run would then be triggered on those workspaces.

That's certainly not exactly what you're asking for here, but the closest thing the platform offers at the moment. 

Given that this is a platform feature request, I'm going to close this but I very much encourage you to submit this request to the [HashiCorp Discuss platform](https://discuss.hashicorp.com/) instead. Thanks!
