### ISSUE TITLE
Not able to recreate managed workspace with provider if it was deleted manually.

### ISSUE THREAD

**Issue by phanclan** [hashicorp/terraform-provider-tfe#195]
If I created a workspace using tfe provider and delete it manually through TFC, then I can't recreate the workspace by applying the config again.

I get the following output.

```
module.hashicat-gcp.tfe_workspace.this: Refreshing state... [id=ws-9QNndHyohP1fuBQf]
...
Error: Error retrieving workspace ws-9QNndHyohP1fuBQf: resource not found
```

**Comment by chrisarcand** [comment]
This should be fixed with https://github.com/hashicorp/terraform-provider-tfe/pull/227 👍🏻
