### ISSUE TITLE
[Feature Request] Updated Workspace to allow for "agent" Operation type.

### ISSUE THREAD

**Issue by straubt1** [hashicorp/terraform-provider-tfe#204]
With the release of TFC for Business, workspaces within TFC can now be configured to run on private agents.

Currently the `tfe_workspace` resource has an argument `operations` that is a boolean.

The request is that this argument is deprecated and a new `execution-mode` argument added, which would be a string that must be one of the following: ["remote", "local", "agent"].

This will allow newer TFC4B users to properly configure a workspace and leverage the new agent feature.

You can manually set this setting with the following payload to `https://app.terraform.io/api/v2/organizations/${tfe_org_name}/workspaces/${WS_ID}`:

```
{
  "data": {
    "id": "${WS_ID}",
    "type": "workspaces",
    "attributes": {
      "environment": "Default",
      "execution-mode": "agent",
      "auto-apply": true,
      "queue_all_runs": true
    },
    "relationships": {
      "agent-pool": {
        "data": {
          "type": "agent-pools",
          "id": "${AGENT_POOL_ID}"
        }
      }
    }
  }
}
```

**Comment by chrisarcand** [comment]
Hello! 

Indeed, modifications for this provider were considered while developing Terraform Cloud Agents. 🎉  Stay tuned, and thanks for your patience! 💞

**Comment by gd-asharov** [comment]
@chrisarcand do you have any updates?

**Comment by nikolay** [comment]
@chrisarcand We manage TFC using Terraform and planning to upgrade to the Business tier, but we'll hate if we have to manually configure self-hosted agents instead of using Terraform itself.

**Comment by chrisarcand** [comment]
Hello again!

No exciting new update at this very moment, but I'll reassure that lots of wheels are spinning and configuration of workspaces for 'agent' execution mode is coming soon - as well as more additions regarding Terraform Cloud Agents. The provider at this point is just waiting for some additions we're releasing for Terraform Cloud itself (which the provider needs, here) and then I'll push up provider support the moment those feature(s) are made available. We expect that to be coming up very quickly here in November.

Thanks for your patience!

**Comment by nikolay** [comment]
Ideally, we want to have multiple pools of agents and the ability to assign multiple pools to a single workspace. Having a single global pool is very limited if you have multiple clouds with multiple physically isolated accounts like having multiple tenants, etc.

**Comment by nikolay** [comment]
Now, that multiple pools and workspace pool assignment is a thing, can we have the provider updated, please?

**Comment by chrisarcand** [comment]
Patience, please.
