### ISSUE TITLE
tfe_team_access resource id not visible anywhere

### ISSUE THREAD

**Issue by hagurganus** [hashicorp/terraform-provider-tfe#25]
I may be overlooking it, but the tfe_team_access resource ID (referenced in the import example for the tfe_team_access resource, [here](https://www.terraform.io/docs/providers/tfe/r/team_access.html#import)), isn't made visible through any existing TFE API endpoint. (Searching [Terraform.io for 'tws-'](https://www.google.com/search?q=%22tws-%22+site%3Aterraform.io&oq=%22tws-%22&aqs=chrome.0.69i59j0j69i57j0l3.3624j0j1&sourceid=chrome&ie=UTF-8) yields only that page.) Is there some other way to retrieve this ID, or is this one of those edge cases where the id can only be gotten once the resource is in the TF state?

Thanks!
Heath

**Comment by svanharmelen** [comment]
Hi @hagurganus, I'm afraid your assumptions are correct. The team access IDs are indeed hard to retrieve.

Besides the option you already suggested yourself (retrieving the ID from the TF state after the team access is created) you can also see the IDs when working in the web UI, but only by using the developer console of your browser while loading the related pages.

Hopefully we can improve this in the future, but for now these seem to be the only options.

**Comment by hagurganus** [comment]
@svanharmelen : Thanks for the follow-up on that.

> you can also see the IDs when working in the web UI, but only by using the developer console of your browser while loading the related pages

Could you tell me which 'related pages' you're referring to here? I tried loading the pTFE workspace access page (i.e. `https://<PTFE-URL>/app/<ORG>/<WORKSPACE-NAME>/access`), and examining the console logs in developer console in Chrome (version 70.0.3538.77), but I couldn't see anything related to the tfe team access resource ID there (i.e. nothing with 'tws-'). (I _did_ see the _workspace ID_ ('ws-...'), so I feel like I'm on the right track here.) I agree this wouldn't be a very user-friendly option, but it'd at least make it technically possible to import an already-created team access resource into TF state.

Any suggestions?

**Comment by svanharmelen** [comment]
@hagurganus if you paste this link in your browser (assuming you have an authenticated session), you get a JSON object which should contain the info you need: `https://<PTFE-URL>/api/v2/team-workspaces?filter%5Bworkspace%5D%5Bid%5D=<WORKSPACE-ID>` (you can also use this URL without the filter).

In the `relationships` field of each result you can find the `team` and `workspace` object that the access applies to.

Does this help?

**Comment by svanharmelen** [comment]
@hagurganus does this help you to get the required IDs you are looking for?
