### ISSUE TITLE
`tfe_workspace` documentation around `oauth_token_id` is misleading`

### ISSUE THREAD

**Issue by bixu** [hashicorp/terraform-provider-tfe#257]
The docs for `tfe_workspace` (https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace)
suggest something like this:

```terraform
  vcs_repo {
    identifier     = ":org/:repo"
    oauth_token_id = var.github_oauth_token_id
  }
```
whereas the correct syntax is
```
 identifier     = "org/repo"
```

**Comment by chrisarcand** [comment]
* Is it the `identifier` or the `oauth_token_id` that seem misleading to you?
* The `oauth_token_id` documentation was actually just changed [here](https://github.com/hashicorp/terraform-provider-tfe/commit/bb36d4d17102b3d1e8b64e39480167125d38de73); it won't be live on the site until the next release.

Happy to

**Comment by bixu** [comment]
@chrisarcand, it's just the bit about identifier. I thrashed on this for a bit before I realized the `:` wasn't part of the string. I'm not sure what the documentation style guide is for you folks, but I usually record placeholder values as `<foo>/<bar>` -- the `:` notation just wasn't clear (to me).

**Comment by chrisarcand** [comment]
Changed in de33c37a219cd587f1566d449101234cfbb16133

Thanks
