### ISSUE TITLE
Question: auto queue plan when tfe modifies a workspace

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-tfe#258]
Is there a way to auto queue the workspace when the tfe provider changes a workspace variable?

**Comment by chrisarcand** [comment]
"Yes" - but there's no native platform feature for queueing runs on variable changes to that same workspace, and no provider feature for queueing a run directly. One such way could be to utilize [Run Triggers](https://www.terraform.io/docs/cloud/workspaces/run-triggers.html) (which can also be managed by this provider). Using two workspaces - one used for provisioning to Terraform Cloud/Enterprise itself - you can provision variables to your target workspace as well as a run trigger using the first as a source.

Then, whenever a variable is changed (provisioned from the other workspace) a run is queued on that workspace via the trigger.

Hope that helps!

**Comment by dkirrane** [comment]
Ok I see, RunTriggers a a bit dumb however.

If tfe-provider is managing 20+ workspaces and my change only updates 1 workspace. Won't the RunTrigger kick off all 20 workspaces?

**Comment by chrisarcand** [comment]
> Ok I see, RunTriggers a a bit dumb however.

I would refrain from calling a feature (be it from HashiCorp or anyone) "dumb", as it's pretty disrespectful to the engineers and designers that put their time and effort in to building it. I think what you mean is that you find that run triggers don't appear to be what you're looking for, exactly. 

Yes, I believe the triggers would queue a run on all linked workspaces, even those unaffected; though those would run a plan that finds no changes, and no action will be required for them. Running a plan _is_ a form of drift detection, a topic of which is beyond the scope of this thread but you can [read more about here.](https://www.hashicorp.com/blog/detecting-and-managing-drift-with-terraform)

This is _one_ such way to auto queue a plan when this provider modifies a workspace, as I said. Others may be more appropriate for your situation if you find that running a plan on every managed workspace to detect potential drift is unacceptable.
