### ISSUE TITLE
auto_apply=true doesn't work when the workspace is kicked off by a run_trigger

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-tfe#261]
If a the workspace uses `auto_apply = true` it will not auto apply when it is kicked off by a `run_triggers   = ["other-workspace"]`

**Comment by chrisarcand** [comment]
Hello! This has nothing to do with the provider actually, and is working in the platform as designed; see [the documentation on Auto Apply:](https://www.terraform.io/docs/cloud/workspaces/settings.html#auto-apply-and-manual-apply)

> Auto-apply has the following exception:
> * Plans queued by users without permission to apply runs for the workspace must be approved by a user who does have permission. (More about permissions.)
> * **Plans queued due to run triggers from another workspace must always be manually applied.**

**Comment by vaficionado** [comment]
> If a the workspace uses `auto_apply = true` it will not auto apply when it is kicked off by a `run_triggers = ["other-workspace"]`

Hi @dkirrane! While Chris is correct and this is working as currently designed. I'd be interested in learning more about how you're using run triggers and autoapply. If you'd be open to discussing further with me, feel free to reply below!
