### ISSUE TITLE
[Feature Request] Add Description Attribute for Workspaces

### ISSUE THREAD

**Issue by petems** [hashicorp/terraform-provider-tfe#266]
Currently not possible to set the description for a workspace with the TF resource

Currently blocked by https://github.com/hashicorp/go-tfe/issues/170

**Comment by petems** [comment]
PR open: https://github.com/hashicorp/terraform-provider-tfe/pull/271

**Comment by nadenf** [comment]
@chrisarcand .. This is already been merged.

Just need to update the description and this can be closed.

**Comment by jsok** [comment]
This is now documented as being supported too: https://github.com/hashicorp/terraform-provider-tfe/pull/308

**Comment by petems** [comment]
Closed via #271 and #308
