### ISSUE TITLE
d/workspace external_id

### ISSUE THREAD

**Issue by mbevc1** [hashicorp/terraform-provider-tfe#268]
Is there any reason to keep this warning https://github.com/hashicorp/terraform-provider-tfe/blob/master/tfe/data_source_workspace.go#L13 ? Assuming in the next release we can remove this from r/ d/ resources?

**Comment by chrisarcand** [comment]
Hi!

As the messages says, [more details this deprecation can be found in the changelog](https://github.com/hashicorp/terraform-provider-tfe/blob/v0.24.0/CHANGELOG.md#0240-january-22-2021):

> All deprecated attributes will be removed 3 months after the release of v0.24.0 (April 21, 2021).

> d/tfe_workspace: The deprecation warning for the external_id attribute will not go away until the attribute is removed in a future version. This is due to a limitation of the Terraform SDK for deprecation warnings on attributes that aren't specified in a configuration. If you have already changed all references to this data source's external_id attribute to the ids attribute, you can ignore the warning.

So - not necessarily the next release, but a release on or past the specified date. 

I do empathize with any annoyance of the deprecation warning not able to be resolved in any way, and hope to remove it ASAP - but this is a common workaround for the limitations of the SDK at the moment and was used from the start of this long migration for workspace IDs. We intend to see it through for at least this particular set of changes.

Thanks!

**Comment by mbevc1** [comment]
Yeah, it's a bit misleading with data resource as it's bot using that argument in the code itself.

**Comment by chrisarcand** [comment]
I agree completely 👍  In my own opinion, I wouldn't use this schema mechanism in the future even if the SDK still doesn't allow for warnings at-access when a configuration is actually evaluated; it just gets too noisy.

Here's the issue tracking this ability, if you're curious: https://github.com/hashicorp/terraform/issues/7569

**Comment by mbevc1** [comment]
Indeed, cheers and thanks for related discussions :+1:
