### ISSUE TITLE
data source to list all organizations in tfe

### ISSUE THREAD

**Issue by scottwinkler** [hashicorp/terraform-provider-tfe#272]
Listing organizations is supported by API

https://www.terraform.io/docs/cloud/api/admin/organizations.html#list-all-organizations

There should be a data source to get all organizations. I currently have to use a shell script custom resources to get this

**Comment by muranant** [comment]
Any update on this would be very helpful.  Good to to get this instead of executing a local exec to fetch this from API

**Comment by chrisarcand** [comment]
This API was _just_ added to [Terraform Cloud's Go client](https://github.com/hashicorp/go-tfe) (a major dependency here in the provider); when a release is made, it will allow for something to be added here.

**Comment by radditude** [comment]
Whoops, forgot to comment here with the updated status of this request! #323 added a data source that looks like this:

```
data "tfe_organizations" "orgs" {
  admin = true 
}
```

When `admin` is true, the data source will use the admin API to grab all organizations in a particular TFE installation. When `admin` is false, it will use the non-admin API to list all organizations available to the user token used for authentication.

This addition will go out in v0.26.0.
