### ISSUE TITLE
tfe_registry_module - allow creation of non-vcs backed module

### ISSUE THREAD

**Issue by CultClassik** [hashicorp/terraform-provider-tfe#276]
We do not use the VCS backing at all with TFE. Everything is done with API calls to TFE from CLI or a custom app. We can't manage our module registry with TF code because it only allows you to create a module that has a vcs block. We need to be able to create the module with TF code and then a cicd pipeline will build and publish the modules afterwards. New feature please? :)

**Comment by chrisarcand** [comment]
Hardly a feature request in my opinion - I'd consider this a bug 😄 Just as with workspaces or policy sets, modules shouldn't have a hard requirement on VCS to source from.

**Comment by brandonc** [comment]
We forgot to close this bug when support was added to the provider for both public and private [registry modules](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/registry_module). Sorry about that!
