### ISSUE TITLE
Can't create Terraform Cloud members using TFE provider

### ISSUE THREAD

**Issue by AndrewDryga** [hashicorp/terraform-provider-tfe#278]
```
###### Plan section

# module.terraform-cloud.tfe_organization_membership.member["andrew@example.com"] will be created
  + resource "tfe_organization_membership" "member" {
      + email        = "andrew@example.com"
      + id           = (known after apply)
      + organization = "org"
      + user_id      = (known after apply)
    }

###### Log

module.terraform-cloud.tfe_organization_membership.member["andrew@example.com"]: Creating...

###### Error

Error: Provider produced inconsistent result after apply

When applying changes to
module.terraform-cloud.tfe_organization_membership.member["andrew@example.com"],
provider "registry.terraform.io/hashicorp/tfe" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Error creating team env-developers for organization talkinto: resource not found

  on ../../modules/terraform-cloud/main.tf line 1, in resource "tfe_team" "developers":
   1: resource "tfe_team" "developers" {

**Comment by AndrewDryga** [comment]
Looks like it was because we did not configure the access token to provider, however, we use Terraform Cloud back-end. Is there any way to reuse the access token that backend is using to avoid adding/managing a new one? I checked documentation and did not find anything, while I feel like this should be a default behaviour for TF Cloud users.

**Comment by brandonc** [comment]
@AndrewDryga I know it's been a long time, but I want to make sure your concern is addressed.

For awhile now the provider has the ability to use the token that is stored in the home directory after running `terraform login`, which is host-specific and shared between the provider and the backend/cloud configuration block.

I'm going to close the issue now, but please let me know if I can clarify anything or help with any other issue.
