### ISSUE TITLE
tfe_registry_module: Error while waiting for module %s/%s to be ingested: resource not found.

### ISSUE THREAD

**Issue by fernanzambrano** [hashicorp/terraform-provider-tfe#283]
Hi,
I have found subject error during execution of next terraform source code:

terraform {
  required_providers {
    github = {
      source = "integrations/github"
      version = "4.5.2"
    }
    tfe = {
      source = "hashicorp/tfe"
      version = "0.24.0"
    }
  }
}

provider "tfe" {
  hostname = "host-tfe"
  token    = "user_token_tfe"
}

#Organization
resource "tfe_organization" "tfe_organization" {
  name  = "fzg-testing"
  email = "email@unknown.com"
}

resource "tfe_oauth_client" "github" {
  organization     = tfe_organization.tfe_organization.name
  api_url          = "https://host/api/v3"
  http_url         = "https://host"
  oauth_token      = "outh_token"
  service_provider = "github"
  depends_on = [
    tfe_organization.tfe_organization
  ]
}

#Publish module
resource "tfe_registry_module" "test-registry-module" {
  vcs_repo {
    display_identifier = "github-org/terraform-aws-fzg-module-test"
    identifier         = "github-org/terraform-aws-fzg-module-test"
    oauth_token_id     = tfe_oauth_client.github.oauth_token_id
  }
}

The code inside github-org/terraform-aws-fzg-module-test is forked from  https://github.com/hashicorp/learn-private-module-aws-s3-webapp.git (an example of module to be published)

I am using: 
- Local Terraform Enterprise with version Release: v202001-7
- An user Token

Could you help me to solve this problem? Is a code bug or an error in my terraform code source?

Thanks in advance and best regards.

**Comment by conzy** [comment]
Experiencing the same issue using GitHub VCS

```
provider "tfe" {
  hostname = "app.terraform.io"
  token    = var.token
  version  = "~> 0.24.0"
}

resource "tfe_registry_module" "terraform-aws-transfer" {
  vcs_repo {
    display_identifier = "${var.github_organization}/terraform-aws-transfer"
    identifier         = "${var.github_organization}/terraform-aws-transfer"
    oauth_token_id = var.vcs_oauth_token_id
  }
}

```

Error:

```
tfe_registry_module.terraform-aws-transfer: Creating...

Error: Error creating registry module from repository my-org/terraform-aws-transfer: resource not found
```

Same module could be added through Terraform Cloud UI using the same VCS provider.

**Comment by fernanzambrano** [comment]
I have found the solution to this issue. Indicated source code works with a newer version of terraform enterprise or terraform cloud. Error is generated by a bug in side server. Backend respond does not match with client response.
