### ISSUE TITLE
tfe_policy_set needs to support uploading tarball with policies

### ISSUE THREAD

**Issue by scottwinkler** [hashicorp/terraform-provider-tfe#289]
From https://www.terraform.io/docs/cloud/api/policy-sets.html#create-a-policy-set-version:

> For versioned policy sets which have no VCS repository attached, versions of policy code may be uploaded directly to the API by creating a new policy set version and, in a subsequent request, uploading a tarball (tar.gz) of data to it.
> 
> POST /policy-sets/:id/versions

There is currently no attribute on tfe_policy_set that allows you to upload a tarball. There is also no corresponding resource that allows you to do this. This should be fixed, because it is supported by the API and there is no reason not to have it.

**Comment by brandonc** [comment]
@scottwinkler Hey, Scott. While it wasn't exactly what you suggested, v0.26.0 (released September '21) contained a feature to specify a slug attribute on tfe_policy_set that should be a data.tfe_slug.source_path. This could be used to tar/gzip and upload policies in a single step.

Sorry we forgot to close this issue at that time! Let me know if I should re-open this feature request to more directly address specifying an existing tar.gz file as opposed to a tfe_slug. As an aside, thanks for Terraform In Action. It was my introduction to Terraform.
