### ISSUE TITLE
Add notifications when new modules versions are released thru tfe_notification_configuration

### ISSUE THREAD

**Issue by yashbhutwala** [hashicorp/terraform-provider-tfe#296]
Use-case:
- I would like to setup slack notifications for when new versions of private modules are published in the private registry.

**Comment by chrisarcand** [comment]
Thanks for opening this! I think notifications around releases of modules would be really neat. As it stands now, the [Notification Configurations API](https://www.terraform.io/docs/cloud/api/notification-configurations.html) is specifically for notifying on the various states of TFC runs and not anything to do with modules. 

What you're asking for is actually a feature request for Terraform Cloud and isn't specific to this provider, which is what this issue tracker is for; so I'm going to go ahead and close this, but I highly encourage you to post this suggestion on discuss.hashicorp.com or through your usual support channel if you're a Terraform Enterprise customer. 🙇‍♂️

**Comment by yashbhutwala** [comment]
Support ticket created, thanks @chrisarcand, I look forward to the feature in TF Cloud 😄
