### ISSUE TITLE
Give ability to run_triggers to watch for specific outputs update in addition to workspace apply

### ISSUE THREAD

**Issue by florian0410** [hashicorp/terraform-provider-tfe#305]
Hello guys,

I was using TFE for my project and I discovered the option **run_triggers** that can be configured using the module **tfe_run_trigger**.

The option is great but I wonder if we could enhance it by adding the possibility to watch for state outputs changes for triggering runs on others workspace instead of a run on the current workspace. 

Note that the limitation of 20 source workspaces could be a bit too limitating but using this new way could help to raise this limit maybe since we would focus more on specific elements.

**Comment by radditude** [comment]
Thanks for opening this! I think this would be a really neat enhancement to the run trigger functionality.

However, this issue tracker isn't a great place to file feature requests for Terraform Cloud itself (as opposed to features that are specific to this provider!). I'm going to go ahead and close this, but I'd encourage you to post this suggestion on [discuss.hashicorp.com](https://discuss.hashicorp.com/), or if you're a Terraform Enterprise or Terraform Cloud for Business customer, you can submit a feature request via support channels.
