### ISSUE TITLE
tfe provider 0.25.0 causing terraform plan errors

### ISSUE THREAD

**Issue by Stromweld** [hashicorp/terraform-provider-tfe#307]
TF CLI 0.14.11 and TFE provider 0.25.0 generate error after refreshing state. 
Error: Error reading remote state consumers workspace ws-7499QnnPns82UrVM: resource not found

Been using TFE provider since 0.22.0 with version constraint ">= 0.22.0". We use the provider to manage and automate gitlab project creation. We've been using this same configuration for almost a year now. Latest provider update started giving us errors now. Locking back to 0.24.0 works and fixes the issue. We don't use external_id anywhere which was deprecated and removed according to changelog.

we use the tfe workspace in a module where we pass it a map(object()) using for_each.

```hcl
resource "tfe_workspace" "workspace" {
  name                           = var.name
  organization               = var.organization
  auto_apply                 = false
  execution_mode        = "remote"
  queue_all_runs          = true
  speculative_enabled = true
  terraform_version     = "0.14.11"
}
```

**Comment by radditude** [comment]
Thanks for reporting, and apologies for the inconvenience! We are currently working on a fix for this issue over in https://github.com/hashicorp/terraform-provider-tfe/pull/303 and hope to release v0.25.1 soon.

**Comment by radditude** [comment]
[v0.25.1](https://registry.terraform.io/providers/hashicorp/tfe/0.25.1) was just released! Please let us know if you experience any issues with the latest version.
