### ISSUE TITLE
Issue creating tfe_workspace with Azure DevOps as the VCS repo

### ISSUE THREAD

**Issue by chac-dee** [hashicorp/terraform-provider-tfe#313]
Hello team, I've got a problem with creating a Terraform Cloud Workspace where the VCS is using Azure DevOps.

Here is my configuration:
```
resource "tfe_workspace" "test" {
  name         = "test-workspace"
  organization = var.organization_id
  vcs_repo {
    identifier     = "<azure_devops_organization>/<azure_devops_repo>"
    branch         = "main"
    oauth_token_id = var.oauth_token_id
  }
}
```
But this is the error message I get:
```
│ Error: Error creating workspace test-workspace for organization <terraform_cloud_organization>: invalid attribute
│ 
│ Repository doesn't exist or isn't accessible
│ 
│   with tfe_workspace.test,
│   on workspaces.tf line 1, in resource "tfe_workspace" "test":
│    1: resource "tfe_workspace" "test" {
```

As specified in the [docs](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace#vcs_repo), the format for the `vcs_repo` `identifier` should be `<organization>/<repository>` whereas in Azure DevOps, repositories are structured like this:
`<azure_devops_organization>/<azure_devops_project>/<azure_devops_repo>`
or in terms of a URL:
https://dev.azure.com/<azure_devops_organization>/<azure_devops_project>/_git/<azure_devops_repo>

Has anyone come across this before?

**Comment by chrisarcand** [comment]
Hi! 

Can you try `<organization>/<project>/_git/<repository>` and let me know if that works? Based on [the documentation of the same argument for registry modules](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/registry_module#identifier), I believe it will; and if so we should add the same reference in the `tfe_workspace` documentation for clarity!

**Comment by chac-dee** [comment]
Hey @chrisarcand, thanks for the reply. That worked!!

**Comment by chac-dee** [comment]
I've opened a [pull request](https://github.com/hashicorp/terraform-provider-tfe/pull/314) just to update that argument description

**Comment by chrisarcand** [comment]
Awesome! Closing this and moving discussion to that PR 👍🏻
