### ISSUE TITLE
resource/tfe_variable: the parameter `sensitive` should be `ForceNew` when removing `sensitive`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-tfe#317]
A variable cannot be converted from `sensitive = true` to `sensitive = false` in-place. The API returns the error

>Sensitive cannot be changed from true to false on saved records. To make this variable readable, destroy this record and create a new one with the same key value.

A `CustomizeDiff` function could be used to set `ForceNew` on `sensitive` if changing from `true` to `false`

**Comment by chrisarcand** [comment]
Indeed, good call!

**Comment by fatbasstard** [comment]
Ah, just got hit with this error... Pretty annoying, would be great if this can be fixed/implemented
