### ISSUE TITLE
Bitbucket Cloud - Repository doesn't exist or isn't accessible

### ISSUE THREAD

**Issue by philippeboyd** [hashicorp/terraform-provider-tfe#324]
I followed the initial steps to configure a git repository, however I'm unable to add it and I get the following **Error creating workspace**.

![image](https://user-images.githubusercontent.com/3239656/120713191-8d01b980-c48f-11eb-948a-22fa57677638.png)

HTTP error is : 
```json
[
  {
    "status": "422",
    "title": "invalid attribute",
    "detail": "Repository doesn't exist or isn't accessible",
    "source": {
      "pointer": "/data/attributes/repository"
    }
  }
]
```

How can I get this error If i successfully passed the step **Choose a repository** ?

**Comment by chrisarcand** [comment]
Hi! Sorry you seem to be having some trouble. The setup process there does not appear to validate the repository until that final step - you can pass anything you want (`foo/bar`) as an identifier and the error will show at the end, not after the third step. I would double check your identifier, your OAuth provider configuration, and the repository itself to be sure it's all correct.

---

Regardless, however, this issue tracker is for the [Terraform Cloud/Enterprise provider](https://registry.terraform.io/providers/hashicorp/tfe/latest) and issues with the platform are not triaged/addressed here; if you continue to have trouble after double checking those things above, please [submit a support request](https://support.hashicorp.com/hc/en-us/requests/new) for more help!
