### ISSUE TITLE
Excessive API calls from tfe_team and tfe_organization_membership data sources

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/terraform-provider-tfe#326]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
Terraform v0.15.5
on darwin_amd64
```

#### Terraform Configuration Files

```terraform
data "tfe_team" "team_lookup" {
  for_each = to_set(var.some_list)

  organization = "some-organization"
  name         = each.value
}

data "tfe_organization_membership" "membership_lookup" {
  for_each = to_set(var.some_other_list)

  organization = "some-organization"
  email        = each.value
}

```

#### Debug Output

N/A

#### Expected Behavior

`tfe_team` and `tfe_organization_membership` data sources won't potentially cause excessive API lookups by paginating through all of the Teams and Organization Memberships in the organization.

#### Actual Behavior

Each `tfe_team` and `tfe_organization_membership`  data source paginates through potentially all Teams and Organization Memberships in the organization, which could lead to performance issues or potentially throttling on the API side.

#### Additional Context

We're using the `tfe` provider heavily to configure our Terraform Cloud teams and their access to workspaces. We will likely have hundreds, and potentially thousands, of `tfe_organization_membership` and `tfe_team` data source lookups - since each one appears to list _every_ organization member and team (albeit exiting early when it finds a match), we may end up issuing tens of thousands of API calls in a short burst when executing a plan.

While we haven't seen issues yet as we're still on-boarding folks to our organization, but we're concerned with the risk of causing excessive API lookups and slowing down our Terraform Cloud runs. I would be open to submitting a PR that adds some sort of caching, but wanted to raise an issue first to get your opinion.

Alternative solutions could be changing the TFE API to allow for `GET` requests for a particular team, rather than having to list every team, and similar for the `tfe_organization_membership` data source.

**Comment by chrisarcand** [comment]
Indeed, this is a very valid request and thank you for raising it. I do think the most appropriate answer may involve API changes as you mentioned.

**Comment by brandonc** [comment]
I think we forgot to close this back in May. Thanks for reporting it.
