### ISSUE TITLE
Add apply_parallelism input to support serial execution

### ISSUE THREAD

**Issue by nadenf** [hashicorp/terraform-provider-tfe#329]
#### Use-cases

There are sometimes [bugs](https://github.com/cloudposse/terraform-aws-eks-cluster/issues/106) which need serial execution i.e.

```
terraform apply -parallelism=1
```

#### Proposal

Provide a new input called "apply_parallelism" which allows you to set this variable per workspace.

**Comment by jweigand** [comment]
@nadenf this is already possible by creating an environment variable in your workspace - use the `tfe_variable` resource to create the variable, set the value to whatever you need. See https://www.terraform.io/cloud-docs/workspaces/variables#parallelism
