### ISSUE TITLE
tfe_oauth_client data source by name

### ISSUE THREAD

**Issue by jonmaestas** [hashicorp/terraform-provider-tfe#332]
#### Use-cases

It would be very beneficial to use a friendly name instead of `oauth_client_id` to lookup an oauth_client. If you have to get the `oauth_client_id` as input, you could have just queried for the `oauth_token_id`.

We are trying to use a "workspace-manager" approach to build workspaces and the worksapces need the `oauth_token_id` to connect the repo to VCS. 

The process to create the VCS connection is external to this "workspace-manager" so we don't have the `oauth_client_id` handy.

#### Attempted Solutions

@djaboxx put together an external lookup solution [here](https://gist.github.com/djaboxx/b9cfe2b87735957af86dcdd24fac491a). 

Here is how you can query for the `id` by `name` using `jq`.
```bash
curl -s \
  https://tfe.my-site.com/api/v2/organizations/my-org/oauth-clients \
  --header "Authorization: Bearer my_token" \
  --header "Content-Type: application/vnd.api+json" \
  | jq '.data[] | select(.attributes.name=="my-vcs-connection-name") | .id'
```

#### Proposal

Very similar to how you can do the lookup of `ssh_key` by `name`, we should also be able to lookup `oauth_client` by `name`.

```hcl
data "tfe_ssh_key" "test" {
  name         = "my-ssh-key-name"
  organization = "my-org-name"
}

# ↑↑↑ this lookup functionality, here ↓↓↓

data "tfe_oauth_client" "client" {
  name         = "my-vcs-connection-name"
  organization = "my-org-name" 
}
```

**Comment by brandonc** [comment]
This feature was added in provider version v0.38.0. Please see [the docs](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/oauth_client#finding-an-oauth-client-by-its-name) or [release notes](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CHANGELOG.md#v0380-october-24-2022) for details. Thanks!
