### ISSUE TITLE
Support workspace tags

### ISSUE THREAD

**Issue by ausmartway** [hashicorp/terraform-provider-tfe#337]
#### Use-cases

Terraform Cloud/Enterprise support tags on workspace now, which makes orgnising/filtering workspaces much easier and the UI will be less crowdy. 

Can the provider please support this feature?#### Attempted Solutions

**Comment by atimush** [comment]
Would be super useful!

**Comment by oswalya** [comment]
Would also vote for this as we strive to do a full automation of TFE.

**Comment by thrashr888** [comment]
I’m working on this in #339. Should be ready soon. I agree it’s a nice addition—I think you’ll like it. :)

**Comment by thrashr888** [comment]
#339 has been shipped 🎉
