### ISSUE TITLE
resource/tfe_workspace: Provide a way to work around manually configured GitHub App VCS configs

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-tfe#338]
Currently, the resource `tfe_workspace` does not allow VCS authentication with the GitHub App method, as described at https://www.terraform.io/docs/cloud/vcs/github-app.html#feature-limitations.

When using the GitHub App method, it would be useful to allow the workspace to be created using Terraform and then for the VCS configuration to be applied manually. Unfortunately, this causes perpetual diffs to be reported by Terraform. If `ignore_changes` is used, any changes to other parameters on the workspace causes an `internal server error` response.

#### Use-cases

Configuring a workspace with GitHub App instead of OAuth

#### Attempted Solutions

1. Create `tfe_workspace` without `vcs_repo`, then manually configure VCS. This works for creation, but leads to a perpetual difference reported by Terraform. Using `ignore_changes` removes the difference, but any updates cause an `internal server error` response.
1. Manually create Workspace and import. This still requires `ignore_changes` and updates cause an `internal server error` response.

#### Proposal

Several possibilities:

1. In the AWS provider, we have a `DiffSuppressFunc` which we use on some optional blocks to allow the Terraform configuration to not specify the block. Setting it to `Computed` in addition to `Optional` might work as well.

```go
func suppressMissingOptionalConfigurationBlock(k, old, new string, d *schema.ResourceData) bool {
	return old == "1" && new == "0"
}
```

1. In Terraform state, when GitHub App is used, the `oauth_token_id` attribute is empty. Diff detection could ignore changes when the attribute is empty and not send the `vcs_repo` in the update operation

**Comment by pksunkara** [comment]
Are there any plans to implement this? This is the most annoying thing about TFE provider IMO, unable to create workspaces.

**Comment by brandonc** [comment]
I agree this could be improved. This could qualify as more of a bug.

**Comment by nfagerlund** [comment]
Aside from the provider behavior though, "internal server error" probably should not be appearing when you do this; exposing a 500 to users is a bug, right?

**Comment by ezzatron** [comment]
I believe this should be resolved if #808 gets merged 🤞

**Comment by lucymhdavies** [comment]
https://github.com/hashicorp/terraform-provider-tfe/pull/808 was indeed merged. Is this still an issue?

**Comment by pksunkara** [comment]
Nope, this can be closed.
