### ISSUE TITLE
Cannot create a workspace with operations = false

### ISSUE THREAD

**Issue by skolsuper** [hashicorp/terraform-provider-tfe#345]
#### Terraform Cloud/Enterprise version

Terraform cloud

#### Terraform version

```plaintext
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/tfe v0.25.3
```

#### Terraform Configuration Files

```terraform
resource "tfe_workspace" "backends" {
  for_each       = local.backend_workspace_names
  organization   = tfe_organization.saleswhale.name
  name           = each.value
  operations     = false # set local execution
  queue_all_runs = false
}

```

#### Expected Behavior

Workspaces are created for each `backend_workspace_names` where remote execution is disabled (`operations = false`)

#### Actual Behavior

Workspaces are created for each `backend_workspace_names` where remote execution is enabled (`operations = true`).

`terraform plan` then plans an update-in-place to change `operations = false -> true` for each workspace, which can be applied successfully. After the second `apply`, remote execution is disabled as intended, and there are no changes in future `plan`s.

#### Additional Context

It's just a minor inconvenience to have to apply everything twice, but it might be a simple fix?  I doubt the `for_each` is relevant but included it just in case.

**Comment by chrisarcand** [comment]
Hi! Thanks for reporting this. I've indeed reproduced it and it's a bug we'll have to fix!

I should note beforehand though that the [`operations` argument is deprecated in favor of `execution_mode`](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace#operations), and using the synonymous `execution_mode = "local"` does indeed work as expected; I'd use that not only as a workaround for now, but permanently.
