### ISSUE TITLE
v2.6.0 provider error

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-provider-tfe#353]
Only upgrading the provider version constraint to `~> 0.26.0` now shows:
```
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/tfe" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: Error retrieving provider meta values from provider request
│
│   with provider["registry.terraform.io/hashicorp/tfe"],
│   on <empty> line 0:
│   (source code not available)
│
│ Error retrieving provider meta values from provider request the hostname
│ and token must be present.
```
This is using Terraform Cloud and `TFE_ENGINE` environment variable is set within the workspace. The runs are remote.

**Comment by nikolay** [comment]
I did not have an explicit provider block before and it worked for ages, but now it seems that at least the minimal provider block is required for it to work with TFC:
```HCL
provider "tfe" {
  hostname = "app.terraform.io"
}
```

**Comment by freimer** [comment]
You can also set a TFE_HOSTNAME env var.

**Comment by nikolay** [comment]
@freimer I never had to do this before (and docs clearly say it defaults to `app.terraform.io`). It needs to be documented as v2.6 is not backward-compatible.

**Comment by chrisarcand** [comment]
Hello! Thanks for reporting this regression, which it indeed is. We've found the issue and will release a bugfix for it shortly.
