### ISSUE TITLE
Create state version option in workspace resource

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-tfe#361]
#### Use-cases
Would like to request option in workspace resource to create (upload) state file and set as current state.
This will help us in migrating state from other backends after creating workspace.

**Comment by brandonc** [comment]
@Sreerag74031 Hey, sorry for the delayed response. I'd like a little more information about your specific use case, (or your previous use case!)

State is a slightly tricky kind of resource for this provider to manage. Simply put, the provider can't perform the kinds of safeguards that ensure that the state that is being created is relevant to both the terraform version of the workspace and the lineage of the previous state that terraform itself can. Here are some other options:

- If you're using a CLI workflow for Terraform Cloud/Enterprise, you'll need to modify your backend config block as a part of the migration. If you use the cloud block, terraform will automatically copy the state to the workspace the first time you initialize it:

```
$ terraform init

Initializing Terraform Cloud...
Do you wish to proceed?
  As part of migrating to Terraform Cloud, Terraform can optionally copy your
  current workspace state to the configured Terraform Cloud workspace.

  Answer "yes" to copy the latest state snapshot to the configured
  Terraform Cloud workspace.

  Answer "no" to ignore the existing state and just activate the configured
  Terraform Cloud workspace with its existing state, if any.

  Should Terraform migrate your existing state?

  Enter a value:
```

- If you use a VCS workspace (connect to github, for example), there is no backend config block to reconfigure, but you can use a logical provider like [multispace](https://registry.terraform.io/providers/mitchellh/multispace/latest/docs) to create an initial run.

Let me know if there is something special about your use case that I am not considering. Thanks again for your patience.

**Comment by nfagerlund** [comment]
For reference when we eventually come back to consider this: I believe this functionality (_if_ implemented as an attribute or block on tfe_workspace, rather than some kind of separate resource) is a close sibling of the tfe_workspace `queue_all_runs` attribute. It's something that's relevant to our behavior at the point when we _create_ the workspace, but should not continue to get managed over the remainder of the workspace's lifespan.
