### ISSUE TITLE
0.26.1 doesn't create tags for workspace with vcs block on the first apply

### ISSUE THREAD

**Issue by ausmartway** [hashicorp/terraform-provider-tfe#371]
#### Terraform Cloud/Enterprise version

I m using the current version of TFC.

#### Terraform version

```plaintext
terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.26.1
```

#### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.0"
  required_providers {
    tfe = ">= 0.26.1"
  }
}

provider "tfe" {

}

resource "tfe_workspace" "workspace" {
    allow_destroy_plan            = true
    auto_apply                    = true
    description                   = "description of the workspace"
    execution_mode                = "remote"
    file_triggers_enabled         = false
    global_remote_state           = false
    name                          = "debug"
    organization                  = "yulei"
    queue_all_runs                = true
    speculative_enabled           = true
    structured_run_output_enabled = true
    tag_names                     = [
        "autoinject",
        "aws",
        "azure",
    ]
    terraform_version             = "1.0.7"
    trigger_prefixes              = []

    vcs_repo {
        identifier         = "ausmartway/debug"
        ingress_submodules = false
        oauth_token_id     = "ot-ojKu4mCdGeqTauNo"
    }
}
```

#### Debug Output

```plaintext
https://gist.github.com/ausmartway/65216bf15cdfc28834c8548740112547
```

#### Expected Behavior

workspace should be created with the correct tags.

#### Actual Behavior

workspace gets created without tags on TFC UI, but the statefile contains the tags. Next terraform plan will report that those tags will be added.
#### Additional Context

If the vcs block is removed then the issue disappears. Not sure how this is related.

**Comment by nikolay** [comment]
@ausmartway It's been reported already: https://github.com/hashicorp/terraform-provider-tfe/issues/359

**Comment by thrashr888** [comment]
This was an issue with the API itself. A fix was just deployed and this should now be working as expected. If this is still an issue, please comment or reopen!
