### ISSUE TITLE
Supporting Variable Sets

### ISSUE THREAD

**Issue by mbevc1** [hashicorp/terraform-provider-tfe#391]
#### Use-cases

New feature released: https://www.hashicorp.com/blog/terraform-cloud-variable-sets-beta-now-available

#### Attempted Solutions

/

#### Proposal

It seems it's already part of API: https://www.terraform.io/docs/cloud/api/variable-sets.html
I recognize it's still in beta, but it would be nice have a resource in TFE for configuring it.

**Comment by madtank** [comment]
Thanks for opening this feature request. What we would need is ability to add variable sets to a workspace. Creating and updating the variable sets would be nice option too.

**Comment by elocke** [comment]
Thanks for submitting this, variable sets solve a problem very elegantly for us but cannot be used easily without the provider supporting them.

**Comment by dkirrane** [comment]
Any ETA for this?

**Comment by madtank** [comment]
> Any ETA for this?

I was told April 2022 timeframe.

**Comment by rorychatterton** [comment]
A couple of items that would be useful for customers like myself when implementing this provider:

### Seperate Set from Assignment objects
Can you please ensure that we have separate objects to handle the creation of the variable set, away from the assignment of that variable set. For example:

_Not this:_
```
resource "tfe_variable_set" "my_set" {
   tfe_workspaces = [...]
}
```

But rather this:
```
resource "tfe_variable_set" "my_set" {}
resource "tfe_variable_set_assignment" "my_set_assignment_ws_1" {
    variable_set = ""
    tfe_workspaces = ""
}

```

We would like this to be able to decouple the creation of global variable sets, from the assignment to workspaces. This particular pain point exists with the policy workspace, and it would be great if we could avoid it here!

### Handle Complex Terraform Objects
The current terraform variable class doesn't handle complex objects. If you want to output a complex object into a terraform managed variable (such as a map of objects), you must convert that object into a string (we normally use json encode). 

This limits the usefulness of the variable provider as you are not able to do type validation on the consuming workspace side. 

I have raised an [issue](https://github.com/hashicorp/terraform-provider-tfe/issues/433) here for resolution in the context of standard variables.

**Comment by Satak** [comment]
This would be very useful 🤞

**Comment by ryanisnan** [comment]
Plus one on this feature!

**Comment by morremeyer** [comment]
That's what a thumbs up reaction is for.

In the future, please don't spam people with notifications just to express your support of an idea.

**Comment by mbevc1** [comment]
Nice one, we have Variable Sets supports merged in and available with 0.30.0!

**Comment by jacobtaunton** [comment]
I'm getting an error adding a workspace to a varset.

resource "tfe_variable_set" "this" {
  name         = "var.varset"
  organization = var.organization
  workspaces   = tfe_workspace.this.id
}

   on ../modules/workspaces/main.tf line 46, in resource "tfe_variable_set" "this":
│   46:   workspaces   = tfe_workspace.this.id
│ 
│ An argument named "workspaces" is not expected here.

**Comment by morremeyer** [comment]
It's `wonkspace_ids`, the docs are wrong here.

The documentation bug is being fixed, there's already a PR for it.

**Comment by madtank** [comment]
> It's `wonkspace_ids`, the docs are wrong here. The documentation bug is being fixed, there's already a PR for it.

That’s sort of funny :)
Thanks!
