### ISSUE TITLE
Support for source-name and source-url on tfe_workspace

### ISSUE THREAD

**Issue by lucymhdavies** [hashicorp/terraform-provider-tfe#392]
#### Use-cases
source-name and source-url are currently listed as beta
https://www.terraform.io/docs/cloud/api/workspaces.html

These result in "Created via \<SOURCE NAME\>" to be displayed on the workspace.

#### Attempted Solutions
N/A as this is not yet implemented

Tempted to do a short-term workaround using a provisioner to update the workspace with a PATCH though:
https://www.terraform.io/docs/cloud/api/workspaces.html#update-a-workspace

#### Proposal
Add the source-name and source-url parameters to the tfe_workspace resource.

I appreciate we may not want to actually do this while those parameters are listed as "beta" though

**Comment by lucymhdavies** [comment]
Update on my workaround idea, for the curious...

I have been successful in using a curl provisioner as a workaround in the past, see: https://github.com/hashicorp/terraform-provider-tfe/issues/383

However, in this case, `source-name` and `source-url` are only available on workspace creation.
Doesn't look like they can be used when updating

**Comment by lucymhdavies** [comment]
The TFE SDK does actually contain `SourceName` and `SourceURL` fields already:
https://github.com/hashicorp/go-tfe/blob/main/workspace.go#L129-L130

So I've added this:
https://github.com/hashicorp/terraform-provider-tfe/compare/main...lucymhdavies:source-name-url

Not had a chance to test it yet though

**Comment by lucymhdavies** [comment]
With a source set...

```
terraform {
  required_providers {
    tfe = {
      source  = "localhost/providers/tfe"
      version = "0.0.1"
    }
  }
}

resource "tfe_workspace" "test" {
  name         = "test-source"
  organization = "lmhd"
  source_name  = "TFE Provider"
  source_url   = "https://github.com/hashicorp/terraform-provider-tfe/issues/392"
}
```

behaves as expected
<img width="788" alt="image" src="https://user-images.githubusercontent.com/1116529/174120979-657ba235-bc50-400e-9481-15fc97b0539f.png">


```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # tfe_workspace.test will be created
  + resource "tfe_workspace" "test" {
      + allow_destroy_plan            = true
      + auto_apply                    = false
      + execution_mode                = (known after apply)
      + file_triggers_enabled         = true
      + global_remote_state           = (known after apply)
      + id                            = (known after apply)
      + name                          = "test-source"
      + operations                    = (known after apply)
      + organization                  = "lmhd"
      + queue_all_runs                = true
      + remote_state_consumer_ids     = (known after apply)
      + source_name                   = "TFE Provider"
      + source_url                    = "https://github.com/hashicorp/terraform-provider-tfe/issues/392"
      + speculative_enabled           = true
      + structured_run_output_enabled = true
      + tag_names                     = (known after apply)
      + terraform_version             = (known after apply)
      + trigger_prefixes              = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

tfe_workspace.test: Creating...
tfe_workspace.test: Creation complete after 0s [id=ws-NmSpLA8E8KXE1ph1]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by annawinkler** [comment]
PR merged 🥳 & closing this issue.
