### ISSUE TITLE
Prevent deletion of workspace with resources

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-tfe#396]
We manage our workspaces using tfe_workspace. Once we accidentally removed a workspace and lost the state data. Could we add a delete protection if workspace is managing resources?

**Comment by brandonc** [comment]
@Sreerag74031 Hello! The platform has added support for this feature, and the provider followed with a new attribute force_delete in [v0.40.0](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CHANGELOG.md#v0400-december-6-2022) that must be set if the workspace has resources.
