### ISSUE TITLE
default value for organization field

### ISSUE THREAD

**Issue by ctrlok** [hashicorp/terraform-provider-tfe#434]
Hello. Great work on supporting TFE plugin. 

I want to propose to set the default value for the `organization` field in multiple resources. 

Now I set the global variable `org_name` for all workspaces, but I need to declare this variable in each tf repo and then teach developers to use it (in keys they want to use tfe_outputs or other things). 

And I can't see any reason, why it can't have a default value - current organization name.

**Comment by brandonc** [comment]
Thanks for this request. I agree that in some circumstances this could be convenient. I worry, though, about the possibility of applying changes to the wrong organization unintentionally, or being confused by the type of error message (usually 404) that would be returned from the API for incorrect cross-org relationships.

One way to overcome this burden is to wrap your tfe resources in a module that accepts an organization variable, then use that variable in all other resources. Would your config support that?

**Comment by brandonc** [comment]
I am going to leave this open as a feature request, but I'd still be interested in hearing your thoughts.

**Comment by ctrlok** [comment]
Hi! Thanks for the reply! 

I fixed my problem with using `data.tfe_organization.default.name` or `local.org_name` or variable from variable_set shared between all workflows `var.org_name` 

My developers use terraform almost without involving the platform team, so the solution you provided makes no difference, while it requires creating modules and pass variables to the modules. 

The main idea is that probably all other providers (aws, google) can set org_name/account_name/etc based on the org name specified in the provider definition.

**Comment by brandonc** [comment]
I'm convinced after looking through GCP's provider project config. Thanks for the additional details.

**Comment by rhughes1** [comment]
@brandonc Would it be valuable as well to be able to set this up as an environment variable like the TFE/TFC token? ie `TFE_ORGANIZATION`?

**Comment by brandonc** [comment]
@rhughes1 Yes, that seems reasonable, too. Added it to #762.

**Comment by ctrlok** [comment]
@brandonc Thanks! It will help a lot!
