### ISSUE TITLE
Using tfe_outputs for different workspaces in same environment

### ISSUE THREAD

**Issue by ctrlok** [hashicorp/terraform-provider-tfe#435]
Hi there. 
I'm trying to do a simple thing — create multiple terraform repositories to share code between environments. 

I was able to do all I wanted, but still, it didn't feel native as it should. 

Let’s say I have two repos with terraform code inside (`infra_repo` and `app_repo`) and three environments (`stage`, `preprod`, `prod`) 

According to documentation, the best practice is to create a 6 workspaces 

* `infra_repo-stage`
* `infra_repo-preprod`
* `infra_repo-prod`
* `app_repo-stage`
* `app_repo-preprod`
* `app_repo-prod`

I want to reuse resources I created in `infra_repo` in staging in my `app_repo` in staging and `infra_repo` in prod in my `app_repo` in prod. 

* `infra_repo-stage` ← `app_repo-stage`
* `infra_repo-preprod` ← `app_repo-preprod`
* `infra_repo-prod` ← `app_repo-prod`

I expect in the future to have app2, app3 … app100 which will use resources created earlier in other apps in the same environment. 

* `infra_repo-prod` ← `app_repo-prod` ← `app_repo100-prod`

## Option 1

I can write some code and create ENV variable inside each workspace with `stage`, `preprod`, or `prod` value, depending on the workspace environment. 

Then I’ll need to define this variable inside my `app_repo` vars.tf

And then I need to guess workspace names based on the previously defined template. 

```
data "tfe_outputs" "infra" {
  organization = var.org
  workspace = "infra_repo-${var.ENV}"
}
```

It works but looks like a hack. Also, I’ll need to teach developers about this template and it limits me from updating this template in the future. 

## Option 2

The alternative option is to create complex variables like 

```
# local.rw is a map of workspaces I'm using to autogenerate them
# It uses pretty complex logic of rendering and default values
# I'll just share rendered example
#{
#  "infra_repo-staging" = {
#    "envs" = "staging"
#    "project" = "infra_repo"
#  },
#  "infra_repo-preprod" = {
#    "envs" = "preprod"
#    "project" = "infra_repo"
#  },
#  "app_repo-staging" = {
#    "envs" = "staging"
#    "project" = "app_repo"
#  }, …… }

resource "tfe_variable" "workspaces" {
  for_each     = tfe_workspace.terraform-projects
  category     = "terraform"
  key          = "workspaces"
  
  # Rendered result of this function for workspaces in staging env is: 
  # {"infra_repo": "infra_repo-staging", "app_repo": "app_repo-staging"} 
  # To other envs it will be different names
  value        = {for k, v in local.rw : v.project => k if v.envs == local.rw[each.key].envs}
  workspace_id = each.value.id
  sensitive    = false
}
```

With those complex variables, I still will need to define `workspaces` variable inside each repo, but it simplified the code, while I’ll able to refer tfe_outputs as a variable 

```
data "tfe_outputs" "infra" {
  organization = var.org
  
  # Commented — how it is now
  # workspace = "infra_repo-${var.ENV}"
  
  workspace = var.workspaces.infra
}
```

Still, this scenario is not possible, while tfe_variable supports only strings, but not complex variables. 

## Option 3

Create different organizations for each environment. 
With different orgs I will be able to have workspaces `infra_repo` and `app_repo` inside each organization. 
Still, it limits me from using local execution_mode, while `terraform { cloud }` definition didn’t support multiple organizations. 

## Option 4 (like a fix for option 3)
Create multiple directories inside each repo for each environment (pointing to different organizations inside `terraform {cloud}`) and store the main terraform code as a module, common for all folders created above.

This is pure ~~terragrunt~~ madness. 

# Conclusion

So, as you can see, I didn’t find an easy way to relate to remote outputs inside the same environment. And I don’t know why, while it’s like a common and expected way to use terraform cloud. 

I found how to do what I need, but it feels and looks like a hack, not as an expected workflow of enterprise software. 

# Possible solutions

## support complex variables in tfe_variable 
As I said earlier, complex variables (like objects) may help, still — we need somehow to put those variables in workspaces, but it’s ok

## tfe_outputs search based on tags 

Something like 
```
data "tfe_outputs" "infra" {
  organization = var.org
  tag_names = [var.ENV, "infra_repo"]
}
```
I know that there is an option, where this search may return more than a single result - let it trigger an exception or something then. It looks much better and more reliable compared to `"infra_repo-${var.ENV}”` I’m using now. 

## multiple organizations inside `terraform {cloud}` definition

It’s the worst way of workspace utilization, still, I’m thinking of switching to multiple organizations, while it’ll be more clear for developers. Also, it helps to share the same variables between the whole environment with `variable sets`

And it really helps if we will be able to search for workspaces between a different organization in `terraform {cloud}` definition, for local execution mode 

I’m still hoping, that there is another, more straightforward way to use tfe_outputs and I’m just missing it. 

Hope any of this makes sense to you. Thanks!

**Comment by apparentlymart** [comment]
Hi @ctrlok! Thanks for sharing this use-case and the writeup of what you considered so far.

I'm not one of the folks who works directly in this repository so I'm not intending this as a direct response to your feedback but I just wanted to note a common existing design for situations where it's desirable to make some data available to a downstream Terraform configuration without directly exposing the implementation detail of where that data is coming from (whether that be from Terraform Cloud workspace outputs or from any other data source): [Data-only modules](https://www.terraform.io/language/modules/develop/composition#data-only-modules).

The idea here is to encapsulate the exact details of where the data comes from inside a shared module which you can then update later if you wish to change how the results are determined.

For example, in your data-only module you could declare the following:

```hcl
variable "environment" {
  type = string

  validation {
    condition     = contains(["stage", "preprod", "prod"], var.environment)
    error_message = "Environment must be \"stage\", \"preprod\", or \"prod\"."
  }
}

locals {
  component_name               = "infra_repo"
  terraform_cloud_organization = "example"
}

data "tfe_outputs" "infra" {
  organization = local.terraform_cloud_organization
  workspace   = "${var.component}-${var.environment}"
}

output "vpc_ids" {
  value = tomap(data.tfe_outputs.infra.values.vpc_ids)
}

# ... and whatever else is interesting to export
```

Then in the calling module:

```
module "infrastructure" {
  source = "../modules/infrastructure-data"

  environment = var.ENV
}
```

The calling module can then use `module.infrastructure.vpc_ids` to access that data without directly encoding where the data came from. If you need to change the source of that data later then you can change the module and have all of the callers immediately use the new scheme. That would include both changing the naming scheme for your Terraform Cloud workspaces and also more severe changes, such as having the infrastructure configuration publish the settings into AWS SSM Parameter Store and have the `infrastructure-data` module read them from there.

This is not to say that there aren't new features this provider could potentially offer to make this smoother in the specific case of using multiple Terraform Cloud workspaces, but I just wanted to share the general solution in case it helps you find a good compromise for the current design of Terraform and Terraform Cloud.

**Comment by chrisarcand** [comment]
Hi! And thanks Martin for your extra context. 

> Hope any of this makes sense to you.

Indeed, it very much does! This was a detailed write-up; thanks for submitting it.

This issue actually pertains more to current limitations within the platform, more so than an issue with how this provider models it. The intended way to achieve what you're trying to do today is definitely the one you're using now (Option 1), where different deployment environments are codified purely by the workspace name. 

You can pull a specific workspace's output values by setting the workspace name according to some convention either via...

* An input variable with the full or partial name of the workspace (your solution, as well as Martin's variation, above)
* Or, as a slight variation, the [`terraform.workspace` expression](https://www.terraform.io/language/expressions/references#filesystem-and-workspace-info). Using various [string functions](https://www.terraform.io/language/functions) you could deduce the environment of the current workspace to fetch the outputs from another within the same environment. This is slightly more complex than your input variable method, but saves you having to necessarily define a separate variable in each workspace when you could programmatically deduce it this way, if that's important to you.

As an aside, we're definitely aware of how modeling multiple deployment environments is largely based on conventions around workspace naming, and looking to potentially make improvements here in the future [outside this provider].
