### ISSUE TITLE
We should be able to rename teams.

### ISSUE THREAD

**Issue by mw-root** [hashicorp/terraform-provider-tfe#439]
For some reason the ForceNew flag is set on the name attribute in the 
[team resource
](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_team.go)
#### Use-cases

Creating a team using tfe provider and updating to rename team.

#### Attempted Solutions
N/A

#### Proposal
It appears that the go-tfe client supports it, I can't think of any reason why ForceNew shouldn't be removed from the name attribute.

**Comment by sebasslash** [comment]
Closing. Resolved in #566
