### ISSUE TITLE
data "tfe_variables" output

### ISSUE THREAD

**Issue by Condabas** [hashicorp/terraform-provider-tfe#444]
#### Use-cases

So I am trying to use the <data "tfe_variables"> source and I am able to get a return. The issue is I do not know how to unpack the array that is coming back. 

My Code:

data "tfe_workspace" "azurerm-stg" {
  organization = "xxxxxx"
  name         = "xxxxx-xxx"
}

data "tfe_variables" "azurerm-stg" {
  workspace_id = data.tfe_workspace.azurerm-stg.id
}

output "azurerm-stg" {
  value = data.tfe_variables.azurerm-stg.*
}

But the furthest down the path I can get with the output is:

[{"env":[],"id":"variables/ws-xyz","terraform":[],"variables":[],"workspace_id":"ws-xyz"}]

How do I get down to seeing the variables themselves? Any other path I try just ends up with a [] result. 

I am trying to pull known key values from a workspace to use in another. They share the same team API key. 

#### Attempted Solutions

output "azurerm-stg" {
  value = data.tfe_variables.azurerm-stg.*
}

output "azurerm-stg" {
  value = data.tfe_variables.azurerm-stg.variables.*
}

output "azurerm-stg" {
  value = data.tfe_variables.azurerm-stg.variables[*]
}

output "azurerm-stg" {
  value = data.tfe_variables.azurerm-stg.variables[0]
}

**Comment by FlorentATo** [comment]
Tip: use code-blocks to make your message easier to read for everyone :)

**Comment by sebasslash** [comment]
Hi Tony! 

So each variable category is a list of maps. Each map will follow the `tfe_variable` schema. For example, if I want to find the first `terraform` variable:

```hcl
output "myvar" {
  value = data.tfe_variables.foobar.terraform[0].value
  # value = data.tfe_variables.foobar.env[0].value for env variables
  # value = data.tfe_variables.foobar.variables[0].value for i/o variables
}
```

It's not super obvious from reading the documentation (at least not to me either), so perhaps we need to improve this!
