### ISSUE TITLE
tfe_outputs - across multiple terraform cloud organizations

### ISSUE THREAD

**Issue by kodalikranthi** [hashicorp/terraform-provider-tfe#456]
#### Use-cases

I have two organizations and one is for prd and other is for dev. How can i get outputs from a workspace, which is in different organization. 
we can use tfe_outputs for the same organization. But, How can i navigate across multuple organizations

#### Attempted Solutions

Any possible solution to add multiple bearer tokens for data block or terraform user token for multiple organizations

**Comment by chrisarcand** [comment]
Hi! Two paths here:

* **If you are using a user token which has access to both organizations**, you can just specify the other organization name as an argument to [`tfe_outputs`](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/outputs).
* **If you want to use a different token for different organizations**,  this can be achieved by [configuring the provider multiple times using aliases](https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations).
