### ISSUE TITLE
Create releases when tagging

### ISSUE THREAD

**Issue by mbevc1** [hashicorp/terraform-provider-tfe#459]
#### Use-cases

When we tag a new release it would be useful to create a GitHub release and include changelog there as well.

#### Attempted Solutions

/

#### Proposal

We could use goreleaser/goreleaser-action@v2 GitHub Action to automatically add/update release when we tag a new version.

**Comment by sebasslash** [comment]
Is there a use case where you'd rather use a GH release instead of `releases.hashicorp.com`?

**Comment by mbevc1** [comment]
I can see 0.31.0 was tagged and released. Thanks :tada:
