### ISSUE TITLE
Import of `variable_set` is undocumented/possibly broken

### ISSUE THREAD

**Issue by morremeyer** [hashicorp/terraform-provider-tfe#464]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version
```plaintext
1.1.7
```

#### Terraform Configuration Files

_Not relevant_

#### Debug Output

`org`,  `varset_name` and `ID` are placeholders for the actual values

```plaintext
❯ terraform import module.workspaces.tfe_variable_set.varset_name 'org/varset_name/varset-ID'
╷
│ Error: Error reading configuration of variable set org/varset_name/varset-ID: invalid variable set ID
```

```plaintext
❯ terraform import module.workspaces.tfe_variable_set.varset_name 'org/varset-ID'
╷
│ Error: Error reading configuration of variable set org/varset-ID: invalid variable set ID
```

#### Expected Behavior
 
One of the above commands should import the variable set

#### Actual Behavior

See error above

#### Additional Context

I could not find any documentation for the import, although the resource has an importer defined: https://github.com/hashicorp/terraform-provider-tfe/blob/a0afb917e3076c2d19cc9b2a5eed4f2f396e8748/tfe/resource_tfe_variable_set.go#L20 which should provide this functionality as far as I understand the code.

**Comment by sebasslash** [comment]
Hi Morre! The importer function this resource uses is `schema.ImportStatePassthrough` which means the external ID of the resource will be written to state and then calls the resource's `Read()` method using that ID to fetch the resource. For Variable Sets, the external ID is in the form of: `varset-kjkN545LH2Sfercv`. We don't support `<org name>/<var set id>` pairs for importing this resource. If this is a feature you're keen on seeing being added to the provider, please submit a new issue explaining how you'd like to import variable sets with a valid use case! Thank you 😁

**Comment by morremeyer** [comment]
@sebasslash Thanks for the clarification. I was mainly unsuccessful because the documentation was not updated yet, which it now is.

For everyone stumbling on this for some reason:

```
terraform import tfe_variable_set.test varset-5rTwnSaRPogw6apb
```
