### ISSUE TITLE
Add a user to a team using its user_id

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-provider-tfe#470]
We manage our Terraform cloud using your provider, but onboarding users is very painful! First, we invite users to the organization by using their company email. Second, after we keep checking if they accepted the invite or not and create their account, they need to provide us with their username. Once they provide that, we create a second PR using their username to add them to the appropriate teams. We would like this to be a single-step process, which, I understand, may not be possible with the current API and TFC backend, but it is something that should be considered as when you have a handful of users, this process is not so time-consuming, but doubling the code necessary to onboard a user is pretty wasteful. Meanwhile, we don't believe manually adding a user to the organization is the right approach as we cannot automatically remove them later when they leave the company. Last, but not least - it would be best that our TFC Terraform plans don't care about usernames, but now we have to know them in order for us to put people in the proper teams.

**Comment by sebasslash** [comment]
Hi Nikolay! You can in fact achieve this through the [Organization Memberships API](https://github.com/hashicorp/terraform-provider-tfe/issues/470); the provider just doesn't support `team_ids` as an argument. How does adding a new attribute `team_ids`  to `r/tfe_organization_membership` sound? 

```hcl
resource "tfe_organization_membership" "myUser" {
  organization = "death-star"
  email = "nikolay@galacticempire.gov"
  team_ids = [ "fighter_squadron", "star-destroyers" ] 
}
```

**Comment by nikolay** [comment]
@sebasslash This would do great! Thank you!

**Comment by faithlum** [comment]
Hi Nikolay, 
Good news! You can already a) invite a user to an organization and b) add them to a team (without waiting for them to accept the invite first) using the `tfe_team_organization_member` resource. 

```
provider "tfe" {
 hostname = var.hostname
}

// create _team1_ and _team2_
resource "tfe_team" "test1" {
  name = "team1"
  organization = var.organization
}

resource "tfe_team" "test2" {
  name = "team2"
  organization = var.organization
}

// create organization membership for the test email (invites user to the org) 
resource "tfe_organization_membership" "test" {
  organization = var.organization
  email = "test@example.com"
}

// attaches user to _team1_
resource "tfe_team_organization_member" "test1" {
  team_id = tfe_team.test1.id
  organization_membership_id = tfe_organization_membership.test.id
}

// attaches user to _team2_
resource "tfe_team_organization_member" "test2" {
  team_id = tfe_team.test2.id
  organization_membership_id = tfe_organization_membership.test.id
}
```
