### ISSUE TITLE
Inappropriate value for attribute "workspace_ids": set of string required. - tfe_variable_set

### ISSUE THREAD

**Issue by tysimo** [hashicorp/terraform-provider-tfe#476]
#### Terraform Cloud/Enterprise version

```plaintext
Terraform Cloud
```

#### Terraform version

```plaintext
Terraform version: 1.1.6
tfe provider version: 0.30.2
```

#### Terraform Configuration Files

```terraform
data "tfe_workspace_ids" "int-workspaces" {
  tag_names    = ["int"]
  organization = data.tfe_organization.org.name
}

resource "tfe_variable_set" "int-env" {
  name          = "int-env"
  organization  = data.tfe_organization.org.name
  workspace_ids = data.tfe_workspace_ids.int-workspaces.ids
}
```

#### Debug Output

```plaintext
https://gist.github.com/tysimo/615e48c11185639bae198dd2724fa7b7
```

#### Expected Behavior

Variable set should get successfully applied to map of workspace ids based off tag.  

#### Actual Behavior

I receive the below error when running the plan.  

```plaintext
Error: Incorrect attribute value type
on variable-sets.tf line 51, in resource "tfe_variable_set" "int-env":
  workspace_ids = data.tfe_workspace_ids.int-workspaces.ids
Inappropriate value for attribute "workspace_ids": set of string required.
```

**Comment by tysimo** [comment]
I was actually able to resolve my issue by changing `workspace_ids = data.tfe_workspace_ids.int-workspaces.ids` to `workspace_ids =  values(data.tfe_workspace_ids.int-workspaces.ids)`.

The documentation at [https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable_set](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable_set) for applying variable sets based on workspace tags probably needs to be corrected.

**Comment by scotttyso** [comment]
I was going to report the exact same thing.  @tysimo yours is simpler.  I would say the documentation needs to be updated for sure because it is incorrect.

**Comment by ausmartway** [comment]
workspace_ids is now deprecated. you can do this as below:
`
//get a list of TFC/E workspaces that has tag 'azure' and 'autoinject'
data "tfe_workspace_ids" "azure-apps" {
  tag_names    = ["azure","autoinject"]
  organization = var.organization
}

#get variable_set id:

data "tfe_variable_set" "azure" {
  name         = "Global Varset for Azure"
  organization = var.organization
}

#Attach workspaces with azure and autoinject tag to Azure variable set.
resource "tfe_workspace_variable_set" "azure" {
  for_each = data.tfe_workspace_ids.azure-apps.ids
  variable_set_id = data.tfe_variable_set.azure.id
  workspace_id    = each.value
}
`

**Comment by brandonc** [comment]
Even though workspace_ids is deprecated, the simplest way to do this is to use the keys function, which returns a set of strings.

```hcl
resource "tfe_variable_set" "int-env" {
  name          = "int-env"
  organization  = data.tfe_organization.org.name
  workspace_ids = keys(data.tfe_workspace_ids.int-workspaces.ids)
}
```
