### ISSUE TITLE
Feature: Extending `tfe_workspace` to include "run status"

### ISSUE THREAD

**Issue by eephillip** [hashicorp/terraform-provider-tfe#481]
#### Use-cases
Would it be possible in the `tfe_workspace` data source component be able to provide the "run status" of the workspace at the time of query.
I was thinking being able to generate github badge derived from this status might be useful. 
![image](https://user-images.githubusercontent.com/470759/165813705-f873bd1a-a917-4e59-99ee-72713c9ddcef.png)

Perhaps this might be available directly in in the workspace settings in the future. 

```
data "tfe_workspace" "test" {
  name         = "my-workspace-name"
  organization = "my-org-name"
}
```

#### Attempted Solutions
A review of the `tfe_workspace` data state output doesn't appear to include this state.
I don't believe this status is available from using any of the direct API calls to terraform.io either.

**Comment by brandonc** [comment]
Hi @eephillip !

There is no single run status per workspace, but workspaces can be locked by a run (or by a user or team, manually) , which I think is the closest we're going to get with the current API.

The Workspaces API defines a locked-by relationship if the workspace is locked that looks like this:

```
"attributes": {
    ...
    "locked": true
},
"relationships": {
  "locked-by": {
    "data": {
      "id": "run-f8TsFrd87o2v5zZd",
      "type": "runs"
    },
    "links": {
     "related": "/api/v2/runs/run-f8TsFrd87o2v5zZd"
    }
  },
  ...
}
```

If a workspace is locked by a run, I think it's OK to assume that the plan is awaiting confirmation or is applying.

Would exposing this information in the workspace datasource fit your needs?

**Comment by eephillip** [comment]
I think for my use case I don't think so. 
I may be trying to use the provider in a non-standard way.

For example, say I'm on gh repo readme, and the repo is using the VCS workflow for terraform cloud. 
I have the automated apply disabled, so a "confirm and apply" from a workspace admin is required.

Lets say that this workspace would benefit from knowing if another related workspace has a pending apply in wait.

I was thinking being able to see that status in the readme as a badge would be helpful.

**Comment by brandonc** [comment]
Can you describe how you are using the provider in conjunction with the badge? It seems like it may be more straightforward to configure your app that generates the badge image to access the TFC API. From there, you can consult the workspaces endpoint to get the current-run, then follow the link to find out the status of the run.

**Comment by sebasslash** [comment]
This is outside the scope of the provider so will be closing (apologies). _However_, your best bet would be to use [Run Notifications](https://www.terraform.io/cloud-docs/workspaces/settings/notifications) in conjunction with Github actions to achieve what you want.
