### ISSUE TITLE
`tfe_workspace` state is updated even when the API call to update it fails

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/terraform-provider-tfe#492]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.17.0
+ provider registry.terraform.io/hashicorp/googleworkspace v0.6.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/tfe v0.30.2
```

#### Terraform Configuration Files

```terraform
resource "tfe_workspace" "workspace" {
  # ...
  vcs_repo {
    identifier     = var.vcs_repo.identifier
    branch         = local.computed_vcs_branch
    oauth_token_id = var.vcs_repo.oauth_token_id
  }
}
```

#### Debug Output

I don't have debug output, and it'd be difficult to get considering the size of our workspace.

#### Expected Behavior

Updates to the `branch` attribute should not persist in the Terraform State if the API call to update the `branch` attribute errored.

#### Actual Behavior

The `branch` attribute was persisted in the Terraform State after the run completed even though the API call to update the `branch` attribute failed.

#### Additional Context

We received the following error:

```
Error: Error updating workspace ws-REDACTED: invalid attribute Branch doesn't exist
with module.workspace_factory["REDACTED"].tfe_workspace.workspace["REDACTED"]
on ../../modules/tfcloud-workspace/main.tf line 13, in resource "tfe_workspace" "workspace":
```

...but on a subsequent run (with `refresh=false`), no change was detected. When looking at the Terraform state, it appears that the state file was updated even though the run errored out.

Obviously if we ran with `refresh=true` this would have worked. That said, I still think it's a bug that the state is updated when the API call fails.

**Comment by sebasslash** [comment]
Closed. Solved with #498
