### ISSUE TITLE
TFC Workspace Update Failing

### ISSUE THREAD

**Issue by dpowley** [hashicorp/terraform-provider-tfe#499]
I want to manage a workspace in TF, but manage the VCS settings for the workspace manually. I have the Terraform code below. The plan ignores the `vcs_repo` settings as expected. However, the apply errors (error below).

#### Terraform Cloud/Enterprise version

TFC

#### Terraform version

```plaintext
1.1.9
```

#### Terraform Configuration Files

```terraform
resource "tfe_workspace" "azure" {
  name         = var.workspace_name
  organization = tfe_organization.org.name

  allow_destroy_plan    = false
  auto_apply            = true
  execution_mode        = "remote"
  file_triggers_enabled = true
  queue_all_runs        = true
  speculative_enabled   = true

  lifecycle {
    ignore_changes = [vcs_repo]
  }
}
```

#### Debug Output

Not going to post the debug output as that has ID's that I don't want shared in a public issue, but here is the error.

```plaintext
│ Error: Error updating workspace <workspace id>: bad request
│
│ invalid oauth_token_id
│
│   with tfe_workspace.workspace,
│   on workspace.tf line 43, in resource "tfe_workspace" "workspace":
│   43: resource "tfe_workspace" "workspace" {
```

#### Expected Behavior

This should have updated successfully.

#### Additional Context

Note that the workspace currently has VCS configured. For workspaces without VCS, this doesn't error.

**Comment by laurenolivia** [comment]
Writing to confirm that I was able to reproduce this issue. I looked into the behavior, and figured out a solution. See details below.

Also linking docs to [tfe_workspace resource](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace) and [tfe_oauth_client resource](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/oauth_client).

The `ignore_changes` argument in the `lifecycle` block is looking for a `vcs_repo` block to ignore. I didn't see the `vcs_repo` block in your config. The `vcs_repo` block supports many arguments, but the two that are required are `identifier` and `oauth_token_id`. The `oauth_token_id` is referenced in the `tfe_oauth_client` resource block. 

When I made these updates to my config, I was able to run a successful `terraform apply`. 

Here's a snippet:

```
resource "tfe_workspace" "test2I" {
  name         = "test-workspace-update-failing-2I"
  organization = "lauren-org"

  allow_destroy_plan    = false
  auto_apply            = true
  execution_mode        = "remote"
  file_triggers_enabled = true
  queue_all_runs        = true
  speculative_enabled   = true
  vcs_repo {
    identifier = "laurenolivia/terraform-tests"
    oauth_token_id = tfe_oauth_client.test.oauth_token_id

  }

  lifecycle {
    ignore_changes = [vcs_repo]
  }
}

resource "tfe_oauth_client" "test" {
  name             = "my-github-oauth-client"
  organization     = "lauren-org"
  api_url          = "https://api.github.com"
  http_url         = "https://github.com"
  oauth_token      = "ghp_xxxxxxxxxxxxxxxx"
  service_provider = "github"
}
```
