### ISSUE TITLE
Lint failures do not describe which file caused the issue

### ISSUE THREAD

**Issue by glennsarti** [hashicorp/terraform-provider-tfe#504]
The new linting workflow is trapping warnings and errors, but doesn't say which file or where in the file the violation is.  This makes debugging a terrible experience.

e.g. I have no idea where to even start trying to find these violations.

![image](https://user-images.githubusercontent.com/5819622/169740613-852eff80-7383-444d-96f0-8572603eb617.png)

**Expected Behaviour**

Linting error output should list which file and location within that file caused the failures.

**Comment by glennsarti** [comment]
If I run the linter using a local docker container, it does output location information

```
tfe/provider_test.go:380:11: sprintfQuotedString: use %q instead of "%s" for quoted strings (gocritic)
                Config: fmt.Sprintf("resource \"tfe_organization\" \"foobar\" {\n name = \"%s\"\nemail = \"admin@company.com\"\n}", organizationName),
```

**Comment by uturunku1** [comment]
@glennsarti Thank you for reporting this! I have opened an internal ticket so the CLI team can take a closer look at this issue.
