### ISSUE TITLE
tfe_oauth_client github_entprise is requiring oauth_token

### ISSUE THREAD

**Issue by jakubikan** [hashicorp/terraform-provider-tfe#506]
#### Terraform version

```plaintext
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.75.1
+ provider registry.terraform.io/hashicorp/github v4.24.1
+ provider registry.terraform.io/hashicorp/tfe v0.31.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0

Your version of Terraform is out of date! The latest version
is 1.2.1. You can update by downloading from https://www.terraform.io/downloads.html
```

#### Terraform Configuration Files

```terraform
resource "tfe_oauth_client" "test" {
  name             = "orbit-github"
  organization     = data.tfe_organization.this.name
  api_url          = "${local.github_url}/api/v3"
  http_url         = local.github_url
  service_provider = "github_enterprise"
  key = "key"
  secret = "secret"
}
```
#### Debug Output

```plaintext
tfe_oauth_client.test: Creating...

Error: Error creating OAuth client for organization org: OAuth token is required

  on main.tf line 54, in resource "tfe_oauth_client" "test":
  54: resource "tfe_oauth_client" "test" {
```

#### Expected Behavior
You should be able to set the key and secret like in the terraform cloud UI

<img width="1078" alt="Screen Shot 2022-05-31 at 08 26 08" src="https://user-images.githubusercontent.com/174327/171107146-89d72cff-c9bf-464f-89b7-2ca640443c7b.png">

#### Actual Behavior
It is not possible to create an oauth client without an oauth token.

**Comment by sebasslash** [comment]
Hi Jakub! Thank you for reporting this issue. 

Unfortunately this can't be accomplished with the provider. In the UI, you can specify a client ID and secret key but it's only half the journey. It relies on the user giving explicit authorization through the VCS provider when TFC redirects to the OAuth link. Only then is a token created and sent back to TFC... this Oauth flow wouldn't be achievable in the provider.
