### ISSUE TITLE
Support Microsoft Teams in Notification Configurations

### ISSUE THREAD

**Issue by sethbacon** [hashicorp/terraform-provider-tfe#509]
It looks like MS Teams is now supported as a Notification destination in the notification settings of the workspace.
![image](https://user-images.githubusercontent.com/14307877/171498435-9b55549c-fc3f-40e9-94c2-f2dc960f7b83.png)

#### Use-cases
Provision MS Teams as a Notification on a workspace.

#### Proposal
Looks like the upstream API doesn't support this yet, but presumably this would just be an update to destination_type.

**Comment by radditude** [comment]
Thanks for reporting! As it happens, there's already a draft PR open to add this support: https://github.com/hashicorp/terraform-provider-tfe/pull/484. That PR should be moving out of draft mode very soon.

**Comment by nfagerlund** [comment]
It looks like PR #484 is merged, so I'm going to close this ticket as fixed! 🙌🏼 It should go out in the next release of the provider, which will hopefully be soon.
