### ISSUE TITLE
Provider doesn't work with the `vault_terraform_cloud_secret_creds` Vault Provider resource

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-provider-tfe#512]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version
```plaintext
Terraform v1.2.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.31.0
+ provider registry.terraform.io/hashicorp/vault v3.6.0
```

#### Terraform Configuration Files

```terraform
provider "tfe" {
  token = vault_terraform_cloud_secret_creds.tfc.token
}

resource "vault_terraform_cloud_secret_creds" "tfc" {
  backend = local.vault_tfc_token[var.environment].backend
  role    = local.vault_tfc_token[var.environment].role
}

locals {
  vault_tfc_token = {
    dev = {
      backend = "acl_cpt/tfc_dev"
      role    = "tfc-orgname-dev-org-token"
    }
    prod = {
      backend = "acl_cpt/tfc_prod"
      role    = "tfc-orgname-prod-org-token"
    }
  }
}
```

#### Debug Output
The most relevant content I could find from debug output was

```plaintext
2022-06-03T02:04:53.078Z [INFO]  ReferenceTransformer: reference not found: "local.vault_tfc_token"
2022-06-03T02:04:53.078Z [INFO]  ReferenceTransformer: reference not found: "local.vault_tfc_token"
```

#### Expected Behavior

TFE Provider should have acquired a TFC API token via the Vault Terraform Secrets Engine using the `vault_terraform_cloud_secret_creds` resource.

#### Actual Behavior

`terraform plan` fails with

```plaintext
Error: Error retrieving provider meta values for internal provider.
│ 
│   with provider["registry.terraform.io/hashicorp/tfe"],
│   on main.tf line 43, in provider "tfe":
│   43: provider "tfe" {
│ 
│ This should never happen; please report it to
│ https://github.com/hashicorp/terraform-provider-tfe/issues
│ 
│ The error received was: "Could not set the token value to string
│ unmarshaling unknown values is not supported"
╵
Operation failed: failed running terraform plan (exit 1)
```

#### Additional Context

The Vault Provider is tracking this issue in https://github.com/hashicorp/terraform-provider-vault/issues/1178.

Im also raising it here because

1. The TFE Provider asked me to and
2. We experienced another issue with this provider which is described in https://github.com/hashicorp/terraform-provider-tfe/issues/511

**Comment by ausfestivus** [comment]
Workaround is described in https://github.com/hashicorp/terraform-provider-vault/issues/1178#issuecomment-1145679242

**Comment by annawinkler** [comment]
Thank you for submitting this issue. We're looking into the problem you've described.

**Comment by annawinkler** [comment]
Please see reply [here](https://github.com/hashicorp/terraform-provider-tfe/issues/511#issuecomment-1149301087).
