### ISSUE TITLE
tfe_organization_module_sharing can share with all organizations

### ISSUE THREAD

**Issue by starlightromero** [hashicorp/terraform-provider-tfe#515]
Allow the resource `tfe_organization_module_sharing` to have a boolean which allows the modules of a given org to be shared with all other orgs.

#### Use-cases
The end goal is to easily share modules with all other organizations and to keep that configuration within Terraform.

#### Attempted Solutions
My current workaround is to first have a data block to get all TFE orgs, then pass that in to `tfe_organization_module_sharing`, being sure to exclude the originating TFE org.

```
data "tfe_organizations" "this" {}

resource "tfe_organization_module_sharing" "this" {
  organization = "example"
  module_consumers = [
    for name in data.tfe_organizations.this.names :
  name if name != "example"]
}
```

#### Proposal
Instead of the code in the above section. The ideal code would look as follows

```
resource "tfe_organization_module_sharing" "this" {
  organization = "example"

  allow_all_module_consumers = true
}
```

**Comment by starlightromero** [comment]
@chrisarcand @lafentres

**Comment by chrisarcand** [comment]
I've been on bereavement leave and lafentres is not a current maintainer of this project. Thanks for your patience. 

Short version: This is a platform request for the TFC/E API and not an actionable request to be handled by this provider. You can direct your feature request to [the TFC/E feature request link here](https://github.com/hashicorp/terraform-provider-tfe/issues/new/choose). 

Longer version: Beyond being a feature request for the API, I don't anticipate this being added as proposed above. Consider that Terraform Cloud is a multitenant platform, and that you'd be sharing all of your private modules with all other users (outside of your company) on the Terraform Cloud platform - in other words, a public module, which is exactly what publishing it on the Terraform Registry is for. 

Longer term a missing grouping mechanism could alleviate this pain for both TFC and TFE, taking the form of establishing trust between organizations (not necessarily owned by you) or more dependence on the Terraform Registry. Both of those are out of scope for this tracker, so I'll close this but again encourage you to submit a request to the link above. 

Thanks!
