### ISSUE TITLE
Latest provider v0.32.0 seems to revert all team accesses to organization owner team

### ISSUE THREAD

**Issue by jcmcken** [hashicorp/terraform-provider-tfe#528]
#### Terraform Cloud/Enterprise version

```
v202112-2
```
#### Terraform version

```plaintext
Terraform v1.2.2
on linux_amd64
```

#### Terraform Configuration Files

```terraform
resource "tfe_team_access" "foo" {
  access = "read"
  team_id = data.tfe_team.foo.id
  workspace_id = tfe_workspace.workspace.id
}
```

Here, ``data.tfe_team.foo.id`` is an additional team we created. The provider seems to ignore this setting and set ``team_id`` to the organization owner team's ID instead.

#### Expected Behavior

If you revert to 0.31.0, our plans show no changes. 

#### Actual Behavior

Once we upgrade to 0.32.0, every single team access in our environment gets updated to point to the organization owner team regardless of what the code says.

**Comment by brandonc** [comment]
@jcmcken Thanks for the report! I think I've found the bug within the new release and will release a patch shortly.
