### ISSUE TITLE
[FR] new argument r/tfe_workspace: destroy resources before destroy workspace

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-tfe#532]
#### Use-cases

right now it is too easy to delete workspaces that is managing resources stored in a state file, leaving dangling resources. It would be good to have an argument on `tfe_workspace` so that delete requests of the workspace require a full and successful `terraform destroy` prior to deleting. The resource delete waiter would wait till the workspace stack destroy was complete .

I understand there is currently no argument on [WorkspaceCreateOptions](https://github.com/hashicorp/go-tfe/blob/f759c448421e160181a240ee1e380c9a2fe41c80/workspace.go#L248) but (without much investigating) I wonder if it would still be possible to achieve this behavior in the resource logic and **what the provider maintainers think of that idea.**

#### Attempted Solutions

 n/a

#### Proposal

New argument for TFE to require a configuration stack to be deleted before the workspace can be deleted. 

```terraform
resource "tfe_workspace" "test" {
  name           = "my-workspace-name"
  organization   = tfe_organization.test-organization.name
  ...
  delete_workspace_require_delete_resources = true
}
```

**Comment by rhughes1** [comment]
@drewmullen So looks like as of 0.39.0 of the provider, you can now set the `force_delete` argument to true/false ([PR](https://github.com/hashicorp/terraform-provider-tfe/pull/675) and [argument documentation](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace#force_delete)) If true, when you run `terraform destroy`, the workspace will be force deleted via the force delete API. If false, then it will use the safe delete API which won't delete the workspace unless the resource count is 0.

As another option as well, I thought you could write a Sentinel policy which checks that the `resource_count` on the `tfe_workspace` being destroyed equals 0 (ie All resources have been destroy on the given workspace). The feature hasn't been released as of yet but could also be another check just in case? Here's the [PR](https://github.com/hashicorp/terraform-provider-tfe/pull/682) for reference about the feature. Note that the `resource_count` is also available today on the `tfe_workspace` data source already too (For reference on a use case: https://github.com/hashicorp/terraform-provider-tfe/pull/682#issuecomment-1314515574).

**Comment by brandonc** [comment]
@drewmullen In addition to the safeguards in v0.39.0, this is another situation where `multispace_run` can perform a destroy run on the workspace before the workspace is destroyed.

```hcl
terraform {
  required_providers {
    multispace = {
      source = "mitchellh/multispace"
    }
  }
}

provider "tfe" {
  hostname = "XXX"
  token = "bcroft"
}

provider "multispace" {
  hostname = "XXX"
  token = "bcroft"
}

resource "tfe_organization" "foo" {
  email = "bcroft@hashicorp.com"
  name = "example-workspace-destroy-plan"
}

resource "tfe_workspace" "foo" {
  organization = tfe_organization.foo.id
  name = "example-workspace-destroy-plan"
}

resource "multispace_run" "foo" {
  organization = tfe_organization.foo.id
  workspace    = tfe_workspace.foo.name
}
```

I have also [created a feature request](https://github.com/hashicorp/terraform-provider-tfe/issues/742) to bring Mitchell's multispace_run resource into this provider.
