### ISSUE TITLE
Get IP addresses of TFE/TFC agents in specified agent pool

### ISSUE THREAD

**Issue by ankek** [hashicorp/terraform-provider-tfe#543]
Hi there, i need to whitelist TFE/TFC agents IP`s 

#### Use-cases
Some cloud providers have no option to define access from ANY public IP like 0.0.0.0/32. Since TFE/TFC agent used for execution we need to get that data manually from TFE/TFC web UI.

**Comment by brandonc** [comment]
This is a duplicate of feature request #493
