### ISSUE TITLE
Support for loopback HTTP requests

### ISSUE THREAD

**Issue by skeggse** [hashicorp/terraform-provider-tfe#548]
#### Use-cases

To decouple the TFE provider from being directly provided sensitive API tokens, it's convenient to route requests to the TFE backend through an HTTP proxy. If, for example, I wanted to do this via [aws-sigv4-proxy](https://github.com/awslabs/aws-sigv4-proxy/), I would configure it with `--port 127.0.0.1:8080` or something like that - and then desire to reconfigure the TFE provider to make _HTTP_ requests via that proxy.

#### Attempted Solutions

Configure just `hostname` to interact with the non-TLS port:

```
$ TFE_HOSTNAME=127.0.0.1:8080 terraform plan
╷
│ Error: Failed to request discovery document: Get "https://127.0.0.1:8080/.well-known/terraform.json": http: server gave HTTP response to HTTPS client
│
│   with provider["registry.terraform.io/hashicorp/tfe"],
│   on main.tf line 1, in provider "tfe":
│    1: provider "tfe" {
│
╵
```

I also tried using something like [ssl-proxy](https://github.com/suyashkumar/ssl-proxy) with `ssl_skip_verify`, but this is an unnecessary inconvenience - it's just another moving part to maintain (and another risk in the supply chain).

#### Proposal

Add an `endpoint` parameter (which maybe deprecates the `hostname`) parameter, which supports a complete origin rather than just a host + port. In other words, support `TFE_ENDPOINT=http://127.0.0.1:8080`.

It's also conceivable that this is a little too much attack surface, so an alternative proposal might look like validating the endpoint to ensure that if it's using HTTP that it's also interacting with a loopback or link-local IP address.

**Comment by laurenolivia** [comment]
Thanks for reporting! I have created a ticket in our team's backlog to take a closer look at this issue. @skeggse
