### ISSUE TITLE
tfe_registry_modules with VCS connection get replaced on every run

### ISSUE THREAD

**Issue by relusc** [hashicorp/terraform-provider-tfe#571]
Hi all,

with provider release 0.34.0 all modules with a `vcs_repo` defined get replaced (removed from registry and added again) on each run. This generates unnecessary noise.

This is most likely due to #546 as `ForceNew` was set to `true` for most input variables. However if I want to set them explicitly, the runs fail as well as it is not allowed to define all of them when `vcs_repo` is set. 

**only `vcs_repo` defined -> replace**:

![image](https://user-images.githubusercontent.com/43575286/181281175-edd269cf-a005-4ec8-9474-2e4be3fa42bf.png)

**all input variables set explicitly**:

```text
"module_provider": only one of `module_provider,vcs_repo` can be specified, but `module_provider,vcs_repo` were specified.
```

**remove the ones mentioned in previous error message**:

```text
"registry_name": all of `module_provider,registry_name` must be specified
```

#### Terraform Cloud/Enterprise version

Terraform Enterprise v202207-1

#### Terraform version

```plaintext
...
```

#### Terraform Configuration Files

```terraform
...
```

#### Debug Output

```plaintext
...
```

#### Expected Behavior

modules do not get replaced on each run

#### Actual Behavior

modules get replaced

**Comment by brandonc** [comment]
Thanks for reporting this! It did not show up in our testing, but should have. We'll get this released today.

**Comment by relusc** [comment]
Nice ! thanks to you and @Uk1288 for the quick fix :) can confirm that the modules do not get replaced with release 0.35.0
