### ISSUE TITLE
DOC: Could you add to the documentation a note saying that the outputs should exists before the usage of tfe_output

### ISSUE THREAD

**Issue by rafitadiaz** [hashicorp/terraform-provider-tfe#583]
The current documentation for the usage of `tfe_output` is like this:

```
This data source is used to retrieve the state outputs for a given workspace.
It enables output values in one Terraform configuration to be used in another.
```

Could you add an additional note specifying that the outputs should be created prior to the usage of the `tfe_output`?
Something like:

```markdown
Please notice that the outputs should be generated prior to the usage of the tfe_output.
If the outputs are not created it will error with:

│ This object does not have an attribute named "xxxx".
```

#### Use-cases

**Workspace 1:**

```terraform
resource "google_service_account" "datasync-agent-staging-skim-staging" {
  account_id   = "test-staging"
  display_name = "test-staging"
  project      = "project1"
}
output "bar" {
  value       = google_service_account.test-staging.email
}
```
**Workspace2:**
```terraform
data "tfe_outputs" "foo" {
  organization = "my-org"
  workspace = "workspace1"
}

module "test" {
  service_account_email = data.tfe_outputs.foo.values.bar
}

```

We though that this code should run ok but instead we found this `object does not have attribute` error, and we couldn't figure out the problem. (The error message doesn't point you to the solution in a intuitive way)

I think that a simply note in the doc could help to understand the right sequence and order of execution.

**Comment by sebasslash** [comment]
Hi Rafa! Apologies on the late reply. I think you've encountered a classic Terraform problem where you're trying to fetch information about a resource that has not been created _yet_ (in this case the API parses a state version's outputs asynchronously and so they are not immediately available). That said, you can possibly use [terraform_remote_state](https://www.terraform.io/cloud-docs/workspaces/state#accessing-state-from-other-workspaces) to share outputs across workspaces in a more direct fashion. 

As another workaround, you could delay the creation of `data.tfe_outputs.foo` using the `time` [provider](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) so as to mimic an `await`. 

I'll create a ticket internally for us to add this information to the provider docs (or perhaps it might be best this is included in the API docs).

**Comment by philomory** [comment]
Could you also add information to the documentation noting that the data from `tfe_outputs` is always statically marked as sensitive and is unusable in any context where the value must be known at plan time (such as `for_each` keys) unless you wrap it in the `nonsensitive()` function?
