### ISSUE TITLE
Tag still exists in UI even it is not being used on any workspaces

### ISSUE THREAD

**Issue by juicybaba** [hashicorp/terraform-provider-tfe#590]
#### Terraform Cloud/Enterprise version

v202205-01

#### Terraform version

```plaintext
1.1.9
```

#### Terraform Configuration Files

```terraform
...
```

#### Debug Output

```plaintext
...
```

#### Expected Behavior

When a tag gets removed from all workspaces, that tag shouldn't be seen under filter and tag management.
This is likely an issue of tfe product other than the provider, let me know if there is a dedicated place to report a product issue.

#### Actual Behavior

The tag can still be seen under filter (0 workspaces are using that tag) and tag management (it shows the tag is in use but I cant find related workspace, and I am the admin of the org)
![image](https://user-images.githubusercontent.com/79539850/183507588-508fb973-fbaf-41d9-b51f-806fbd647046.png)
![image](https://user-images.githubusercontent.com/79539850/183507695-d7bd2dcb-e279-47ca-8c1f-e81248425f0f.png)

**Comment by ausmartway** [comment]
why can't you have a tag but not associate it with any workspace?

**Comment by henryxuteck** [comment]
> why can't you have a tag but not associate it with any workspace?

@ausmartway thanks for the reply, there are 2 things, 
1. Creating a tag without associating workspace doesn't seem to be supported, I don't see a "create tag" button.
2. According to the tag details(1st screenshot), there are still 31 instances (i guess instance means workspace) using "2022Apr" tag, but I can't find any workspace associated with "2022Apr" tag (2nd screenshot).

**Comment by juicybaba** [comment]
@ausmartway any update for this ? or there is a better place for TFE platform?

**Comment by juicybaba** [comment]
I think the tag is not being handled properly in general on TFE platform level, where the tag will be created along with workspace, but it will not be removed even all related workspaces are removed.

**Comment by brandonc** [comment]
Tags are not meant to be create-able or delete-able entities on the platform but we also don't delete them once they are unused by any workspace. You are right that this is an issue on the underlying platform, so I've added this as a feature request internally. I don't think a workaround/fix is possible in hashicorp/tfe.
