### ISSUE TITLE
output suppressed due to sensitive value in config. But it's not sensitive

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-tfe#639]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/tfe v0.37.0
```

#### Terraform Configuration Files

**workspace-1**
```terraform
variable "location" {
  type    = string
  default = "eastus"
}

output "location" {
  value = var.location
}
```

**workspace-2**
```terraform
data "tfe_outputs" "workspace_one" {
  organization = "MyOrg"
  workspace    = "workspace-1"
}

locals {
  location = data.tfe_outputs.workspace_one.values.location
}

resource "null_resource" "this" {
  triggers = {
    timestamp = timestamp()
  }

  provisioner "local-exec" {
    command = "echo Location = ${local.location}"
  }
}
```

#### Output
```plaintext
null_resource.this: Provisioning with 'local-exec'...
null_resource.this (local-exec): (output suppressed due to sensitive value in config)
```

#### Expected Behavior

`local.location` should not be sensitive

#### Actual Behavior

`local.location` is considered sensitive

**Comment by brandonc** [comment]
@dkirrane The entire `tfe_outputs` data source schema must be marked as sensitive because it _may_ contain sensitive values and the data source can't know ahead of time. Using the [nonsensitive](https://www.terraform.io/language/functions/nonsensitive) function, you can overcome this by explicitly marking a value as not sensitive:

```
locals {
  location = nonsensitive(data.tfe_outputs.workspace_one.values.location)
}
```

**Comment by dkirrane** [comment]
@brandonc - Just to add this should probably be highlighted in the docs, if not already.
The knock on effect of moving from `terraform_remote_state` to the `tfe_outputs` datasource is that you'll end up with a lot of `sensitive` changes in the plan that look like this

![image](https://user-images.githubusercontent.com/1280116/193855741-dfe9cdb7-9880-445f-bf44-eef5fa6770e7.png)

**Comment by philomory** [comment]
This is a particularly big problem if you're migrating from `terraform_remote_state` and relied on iterating over outputs from another workspace in e.g. `for_each`; you need to start wrapping everything in `nonsensitive()`, which isn't obvious, and it isn't documented (I mean, the function itself is documented in the documentation of available functions, but the fact that you need to start using it everywhere when you migrate from terraform_remote_state to tfe_outputs certainly is not).

**Comment by brandonc** [comment]
@philomory Yes, I agree this is a little vexing and unexpected. I'll get the ball rolling on some documentation improvements with some examples and better explanation.

**Comment by philomory** [comment]
@brandonc For reference, I've just filed #666 suggesting a different solution, because I think recommending us of `nonsensitive`, a highly "privileged" function, as a day-to-day-operations workaround for this issue is maybe not the *best* idea.
