### ISSUE TITLE
TFE Provider doesn't modify the assessment setting with the tfe_workspace resource

### ISSUE THREAD

**Issue by 51r** [hashicorp/terraform-provider-tfe#640]
#### Terraform Cloud/Enterprise version

Terraform Cloud for Business

#### Terraform version

```plaintext
Terraform v1.3.1
on darwin_arm64
```

#### Terraform Configuration Files

The assessment setting in Terraform Cloud Workspace is currently enabled. Thus -   assessments_enabled = "true", 

the Terraform configuration contains the following resource:

```terraform
resource "tfe_workspace" "test-workspace" {
  name                = "terraform-tfe-provider-workspace"
  organization        = "TFCB_org"
  assessments_enabled = "false"
}
```

#### Debug Output

```plaintext
https://gist.github.com/51r/bd7d38265fdde134c514a6d2df61a033
```

This is what the debug log include:

```
  2022-09-30T15:41:48.613+0300 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/tfe\"]" produced an unexpected new value for tfe_workspace.test-workspace2, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .assessments_enabled: was cty.True, but now cty.False
```

#### Expected Behavior

The TFE Provider should modify the assessment setting even when the only argument in the resource block is the `assessments_enabled = "false"`

#### Actual Behavior

When the assessment argument  - `assessments_enabled` is the only argument being changed in the tfe_workspace resource block, the provider doesn't send a PATCH request. 

#### Additional Context

If you add another argument, for example, "description" it will send out the PATCH request and it will modify the assessment settings.

The tfe_provider used is the official latest version `registry.terraform.io/hashicorp/tfe v0.37.0`

**Comment by laurenolivia** [comment]
@51r Thank you for submitting this ticket. We will look into this issue!
