### ISSUE TITLE
tfe_notification_configuration not supporting assessment:drifted and assessment:check_failure and "assessment:failed

### ISSUE THREAD

**Issue by kingatlas** [hashicorp/terraform-provider-tfe#652]
#### Use-cases
I want to use `tfe_notification_configuration` to configure drift detection notification for slack for all our workspaces (>50).

#### Attempted Solutions
I tried to use `assessment:*` trigger as described in the [api](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/notification-configurations) (and also as shown by terraform plan and a manual modification on terraform cloud).
```terraform
resource "tfe_notification_configuration" "notifications" {
  for_each          = { for layer in local.agent_layers : layer.name => layer }
  name             = "${each.key}-notification-configuration"
  enabled          = true
  destination_type = "slack"
  triggers         = ["run:errored", "run:completed", "assessment:check_failure", "assessment:drifted", "assessment:failed"]
  url              = var.slack_webhook_url
  workspace_id     = tfe_workspace.workspaces[each.key].id
}
```
But I get the following error when calling `terraform apply`:
```
│ Error: expected triggers.1 to be one of [run:created run:planning run:needs_attention run:applying run:completed run:errored], got assessment:drifted
│ 
│   with tfe_notification_configuration.notifications,
│   on main.tf line 145, in resource "tfe_notification_configuration" "notifications":
│  145:   triggers         = ["run:errored", "run:completed", "assessment:check_failure", "assessment:drifted", "assessment:failed"]
```

#### Proposal
Support drift detection feature in this official provider. 
This makes it otherwise unusable through automated configuration.

**Comment by annawinkler** [comment]
👋 Hi - thank you for submitting this issue. We've added it to our backlog.

**Comment by lucymhdavies** [comment]
I was just looking into this myself.
(Disclaimer, while I do work for HashiCorp, I'm not on the Terraform team, so treat my response accordingly)


Adding this to the TFE provider relies on a new version of the TFE SDK, https://github.com/hashicorp/go-tfe, to enable this functionality.

In addition, while I do not speak for the Terraform team, there is precedent for holding off on updating the provider while new features are in beta.



As a workaround for now, you can make use of something like the Terracurl provider to interact with the API directly:
https://registry.terraform.io/providers/devops-rob/terracurl/


In my case, my configuration looks like this:

```
resource "terracurl_request" "health_check_notifications" {
  for_each = local.workspaces

  name   = "health_check"
  url    = "https://app.terraform.io/api/v2/workspaces/${tfe_workspace.workspace[each.key].id}/notification-configurations"
  method = "POST"

  headers = {
    Authorization = "Bearer ${local.tfc_token}"
    Content-Type  = "application/vnd.api+json"
  }
  response_codes = [201]

  request_body = <<EOF
{
  "data": {
    "type": "notification-configuration",
    "attributes": {
      "destination-type": "slack",
      "enabled": true,
      "name": "Health Checks",
      "url": "${var.slack_webhook}",
      "triggers": [
        "assessment:check_failure",
        "assessment:drifted",
        "assessment:failed"
      ]
    }
  }
}
EOF

}
```

**Comment by kingatlas** [comment]
Thank you @ lucymhdavies for the trick, I will definitely try it. Better than clicking on ~100 workspaces.

**Comment by brandonc** [comment]
@kingatlas Hello! Drift detection notification triggers were added in release [v0.39.0](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CHANGELOG.md#v0390-november-18-2022).

**Comment by kingatlas** [comment]
thank you @brandonc I just tried it and it is working as expected.
