### ISSUE TITLE
`tfe_nonsensitive_outputs` data source

### ISSUE THREAD

**Issue by philomory** [hashicorp/terraform-provider-tfe#666]
#### Use-cases
The `tfe_outputs` data source always flags its values as sensitive, because sometimes workspace outputs are sensitive, and the sensitivity of a property (in this case, `values`), is set statically at the schema level, so it must be either always-sensitive or never-sensitive. The `tfe` provider, understandably, opts for always-sensitive, to avoid potentially exposing sensitive data.

That said, a lot of workspace outputs are not, in fact, sensitive, and many workspaces have no sensitive outputs at all. Further, there are important contexts in which sensitive values cannot be used, most notably in the `for_each` metaparameter. It would be nice to have a (good) solution for this dilemma.

#### Attempted Solutions
Currently, various responses to issues in this repository recommend using the `nonsensitive` function to unwrap the values returned by the `tfe_outputs` data source, in order to make use of them. See, for example, the response to #373, a proposal similar in some ways to this one.

The problem with this suggestion (besides the fact that the `tfe_outputs` documentation doesn't mention it) is that the `nonsensitive` function is a highly "sensitive" function (for lack of a better term); as the documentation for the function states, "Use this function only when you've derived a new value from a sensitive value in a way that eliminates the sensitive portions of the value". The documentation further states (emphasis in original): "**Use this function sparingly and only with due care.**".

Encouraging the use of the `nonsensitive` function as a way to work-around the fact that the provider is flagging as sensitive values that were never really sensitive in the first place, will necessarily lead to extensive use of that previously use-with-care function as a normal part of day-to-day operations. It will become commonplace to see `nonsensitive` scattered throughout root modules; indeed, depending on the values in question some organizations will likely end up wrapping every single instance of `tfe_outputs` across all workspaces in `nonsensitive`. This is a bad idea, because it means usage of `nonsensitive` to unwrap _actually_ sensitive values will look unremarkable, and may slip through unnoticed.

#### Proposal
I suggest the introduction of a new data source, `tfe_nonsensitive_outputs`; this data source would function exactly as the `tfe_outputs` data source, with two exceptions:

1. The `tfe_nonsensitive_outputs` data source only returns values that are _not_ flagged as sensitive in the source workspace. Any sensitive outputs from the source workspace are entirely omitted from the output of the data source.
2. The `tfe_nonsensitive_outputs` data source has its `values` attribute statically marked as non-sensitive.

In this manner, `tfe_nonsensitive_outputs` can be used for retrieving normal, non-sensitive output values from other workspaces, ready for immediate use; the `nonsensitive` function can be reserved for exceptional use-cases deserving of high-scrutiny, as was originally intended; and users who actually need to retrieve sensitive outputs from other workspaces can continue fetching them via the `tfe_outputs` data source, while thinking carefully about whether and when to unwrap them.

**Comment by brandonc** [comment]
I like this suggestion. It may be better to structure it as a new field `nonsensitive_values` of tfe_outputs data source, though:

```
data "tfe_outputs" "example" {
  organization = "org"
  workspace = "production-app"
}

output "example" {
  value = data.tfe_outputs.example.nonsensitive_values.certainly_safe
}
```

**Comment by philomory** [comment]
Exciting!
