### ISSUE TITLE
d/tfe_team bug

### ISSUE THREAD

**Issue by ikunduraci** [hashicorp/terraform-provider-tfe#683]
#### Terraform version

```plaintext
1.3.4
```

#### Terraform Configuration Files

```terraform
# Grab the team ID
data "tfe_team" "tfe_team_id" {
  organization = var.workspace_organization
  name = var.workspace_team
}
```

#### Debug Output

```plaintext
Error: Could not find team <redacted>/<team-name>
with module.tfe_workspace["my-test.yaml"].data.tfe_team.tfe_team_id
on .terraform/modules/tfe_workspace/main.tf line 8, in data "tfe_team" "tfe_team_id":

data "tfe_team" "tfe_team_id" {
```

#### Expected Behavior

team_id returned

#### Actual Behavior

"Could not find team"

#### Additional Context

I noticed in the trace logs that the path is incorrect.. For example, it seems to try to hit;
`https://app.terraform.io/api/v2/organizations/<redacted>/teams?filter%5Bnames%5D=<team-name>\u0026page%5Bnumber%5D=1\u0026page%5Bsize%5D=20` 
which via a simple CURL doesn't return any results.. if i remove the bit after `<team-name>`, the result is returned correctly i.e. if i run a CURL against
`https://app.terraform.io/api/v2/organizations/<redacted>/teams?filter%5Bnames%5D=<team-name>`.

**Comment by laurenolivia** [comment]
@ikunduraci Thank you for submitting this issue. We will look into this.

**Comment by laurenolivia** [comment]
Hi @ikunduraci. Looks like there might be two separate issues here. 

I was able to successfully read a team ID. So I'd like to verify a few details with your config. I've also pasted my config, below.

Can you please confirm that `hostname` in the `provider "tfe" {}` block points to the correct environment? If `hostname` is not specified, it will default to prod.

```
provider "tfe" {
  hostname = var.hostname
  token    = var.token
  version  = "~> 0.38.0"
}
```

Also, it looks like your query parameters have a couple errors. Parameters should be separated using the ampersand `&`. Try this:

```
https://app.terraform.io/api/v2/organizations/<redacted>/teams?filter%5Bnames%5D=<team-name>&page%5Bnumber%5D=1&%5Bsize%5D=20
```

Lastly, here is my sample config:

```
terraform {
  required_providers {
    tfe = {
      source  = "hashicorp/tfe"
      version = "0.38.0"
    }
  }
}

provider "tfe" {
  hostname = "some-local-url.io"
  token = "localurltoken"
}

data "tfe_team" "test" {
  name         = "readable"
  organization = "hashicorp"
}

output "team_output"{
  value = data.tfe_team.test
}
```

**Comment by ikunduraci** [comment]
Hi @laurenolivia,

Thanks for looking into this - I'm using Terraform cloud with remote execution mode so the hostname should default to `app.terraform.io`.

As for the query parameters, the output I provided above is from the trace log output; I suspect some sort of issue with the encoding on the container running the job in Hashicorp's environment?

Thanks for your help

**Comment by ikunduraci** [comment]
Hi @laurenolivia 

Thanks for your help - it looks to be a permissions issue. I'm unable to enumerate teams using a teams token however am able to using either my user token (which I've got org-level admin permissions for) or an organisation token.

I'll be closing the issue.

Cheers
