### ISSUE TITLE
tfe project rename

### ISSUE THREAD

**Issue by josh-barker** [hashicorp/terraform-provider-tfe#714]
Hi, I tried using the provider to rename a TFC project, but it didn't work.
However, I'm able to rename the project in the UI.

#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
terraform version
Terraform v1.3.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.40.0
```

#### Terraform Configuration Files

```terraform
resource "tfe_project" "name" {
  name         = "Bob"
  organization = "xxx"
}
```

terraform apply

```terraform
resource "tfe_project" "name" {
  name         = "A Bob"
  organization = "xxx"
}
```

terraform apply

#### Debug Output

```plaintext
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # tfe_project.name will be updated in-place
  ~ resource "tfe_project" "name" {
        id           = "prj-U5jysRCmqkPJhVxj"
      ~ name         = "Bob" -> "A Bob"
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
tfe_project.name: Modifying... [id=prj-U5jysRCmqkPJhVxj]
╷
│ Error: Error updating project prj-U5jysRCmqkPJhVxj: invalid value for name
│ 
│   with tfe_project.name,
│   on main.tf line 114, in resource "tfe_project" "name":
│  114: resource "tfe_project" "name" {
```

#### Expected Behavior

The Project name is updated

#### Actual Behavior

It didn't update

**Comment by brandonc** [comment]
Hey, @josh-barker thanks for the bug report. Our underlying SDK is validating project names as IDs. The space in your example (or anything other than alphanumeric, dashes, underscores, or periods) is getting kicked out by mistake.

I'm tracking the issue at https://github.com/hashicorp/go-tfe/issues/607 and we'll release a patch version soon.

**Comment by josh-barker** [comment]
Thanks for the quick response @brandonc !

**Comment by juicybaba** [comment]
Is there any doc for `tfe_project` feature? Like what does it do, where to enable it.

**Comment by shernandez5** [comment]
@juicybaba the Terraform Projects feature is planned to GA in TFC mid January. At that time docs will become publicly available.

**Comment by juicybaba** [comment]
> @juicybaba the Terraform Projects feature is planned to GA in TFC mid January. At that time docs will become publicly available.

 cool, thanks for the info.
