### ISSUE TITLE
tfe_organization not found

### ISSUE THREAD

**Issue by UnderFenex** [hashicorp/terraform-provider-tfe#746]
I'm able to connect to my organization by creating workspaces with:
```sh
terraform workspace new prod
```

Using this backend config:
```sh
terraform {
  backend "remote" {
    organization = "my-org"

    workspaces {
      prefix = "tfe-"
    }
  }

  required_providers {
    tfe = {
      source  = "hashicorp/tfe"
      version = "0.40.0"
    }
  }
}
```

```sh
resource "tfe_organization" "this" {
  name  = "my-org"
  email = "my-email"
}
```
But when I want to import the organization using it's name I got that the resource doesn't exist.

**Comment by brandonc** [comment]
Please ensure that the provider is configured with a token that is able to read the my-org organization. The platform will return 404 Not Found when you have sent a valid token but that token can't be used to read the specified org. Often times, you may have TFE_TOKEN set to something when you expect the credentials from `terraform login` to be used. You can check to see how the provider is being authenticated by reading the debug log:

`TF_LOG_PROVIDER=debug terraform import tfe_organization.this my-org`

**Comment by UnderFenex** [comment]
TFE_TOKEN was required to be in the varset in Terraform Cloud as the backend was remote.
Thanks @brandonc
