### ISSUE TITLE
tfe_notification_configuration not accepting email_addresses attribute

### ISSUE THREAD

**Issue by ninjadude333** [hashicorp/terraform-provider-tfe#757]
#### Terraform Cloud/Enterprise version
Terraform Cloud Ent

#### Terraform version

```
Terraform v1.3.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.49.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/tfe v0.40.0
```

#### Terraform Configuration Files

resource "tfe_notification_configuration" "app1_notifications" {
  name             = "my-email-notification-for-APP1"
  enabled          = true
  destination_type = "email"
  email_user_ids   = [data.tfe_organization_membership.davidg.user_id]
  email_addresses  = ["davidg@terasky.com"]
  triggers         = ["run:created", "run:planning", "run:errored"]
  workspace_id     = tfe_workspace.xyz.id
}

#### Debug Output

```
│ Error: Error creating notification configuration my-email-notification-for-APP1: invalid attribute
│
│ Email addresses not allowed on Terraform Cloud
│
│   with tfe_notification_configuration.app1_notifications,
│   on notifications.tf line 14, in resource "tfe_notification_configuration" "app1_notifications":
│   14: resource "tfe_notification_configuration" "app1_notifications" {
```

**Comment by brandonc** [comment]
@ninjadude333 `email_addresses` is provided for backwards-compatibility with older versions of Terraform Enterprise and is mutually exclusive with `email_user_ids`. In your case, `email_user_ids` is the only argument that is necessary. The docs mention that `email_addresses` is for Terraform Enterprise use only, but it appears to me that this isn't always strictly true so I think the docs could be improved to mention which versions of Terraform Enterprise.

**Comment by ninjadude333** [comment]
amazing, thanks :)
