### ISSUE TITLE
Add manage_projects attribute to the tfe_team resource

### ISSUE THREAD

**Issue by rhughes1** [hashicorp/terraform-provider-tfe#770]
#### Use-cases
In order to grant a team permission to manage projects within their organization, there should be a boolean flag to enable/disable the permission.

#### Proposal
There should be a `manage_projects` attribute under the tfe_team resource to control a team managing projects.

```hcl
resource "tfe_team" "foobar" {
  name         = "team-test"
  organization = "test-organization"
  visibility = "organization"
  organization_access {
	manage_projects = true
  }
}
```

**Comment by laurenolivia** [comment]
Thank you @rhughes1. Our team will look into this.
