### ISSUE TITLE
Add tfe_project data source

### ISSUE THREAD

**Issue by smkillen** [hashicorp/terraform-provider-tfe#782]
#### Use-cases

As part of using the new `tfe_project` resource, it would be useful to be able to also lookup project_id from a pre-existing project, please could the corresponding data resource be added to the provider so that I can use

```
data.tfe_project.main.id
```
in code.

**Comment by nfagerlund** [comment]
Agreed, this definitely should exist. 👍🏼 I'll add that to our ticket queue and see if we can get someone working on it soon.

**Comment by melonger** [comment]
This should be a little more elaborate than just a project ID. I would expect that a type of containerization for organizational value, would provide lists of resources that associate to it. 

Meaning, we should be able to dynamically pull the list as objects associate to the project, so we can leverage in queries and logic for configuration patterns in for_each loops. 

Ex: Can I pull a list of the workspaces associated to the project, so I can properly add permissions, remote state sharing, variable sets, etc... etc.. 

This is a top level bucket, I want to see in the bucket :)

**Comment by pksunkara** [comment]
1. How do this work for the default project though? The name could be changed in the app and that would lead to issues. I would prefer if there's also `data.tfe_default_project` support.
2. How do we manage the name of the default project? I don't see any current way to do this. Should there be `resource.tfe_default_project` that updates name instead of creating it?

**Comment by jacobtaunton** [comment]
@smkillen thanks for opening this feature request! Having a data block for project_id will be very helpful for us.

**Comment by ash-dey-sa** [comment]
Seems to be a quite obvious one, needed badly to keep our terrfaorm cloud fully automated and managed by code only.

**Comment by pedrosaxu** [comment]
> As a workaround until the project_id data block is available, here is an example of how to create projects with the tfe provider and tfe_project resource that has a tf output for the project id. Below that is a separate repository that tests leveraging that output in the creation of a new workspace.
> 
> https://github.com/omeeomi/tfc-project-mgmt https://github.com/omeeomi/tfc-project-list-test

Thanks @omeeomi. Quite a workaround, but seems to work for now. 👍🏻

**Comment by melonger** [comment]
Any Update on the progress on this?

**Comment by nfagerlund** [comment]
As of provider version 0.44.0, released yesterday, this totally exists. It takes an org ID and project name, and exposes a project ID and a list of associated workspace IDs. [Please enjoy your newfound powers.](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/project)

**Comment by guirgouveia** [comment]
> As of provider version 0.44.0, released yesterday, this totally exists. It takes an org ID and project name, and exposes a project ID and a list of associated workspace IDs. [Please enjoy your newfound powers.](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/project)

This data source keeps giving me the error:

│ Error: could not find project <org-name>/<project-name>
│
│   with module.tfe.data.tfe_project.main,
│   on .terraform/modules/tfe/tfe/main.tf line 1, in data "tfe_project" "main":
│    1: data "tfe_project" "main" {

**Comment by zhimsel** [comment]
I'm curious why looking up a project by _ID_ wasn't included? I haven't found a way with this provider to get the name of a project from its ID.
