### ISSUE TITLE
`tfe_variable_set` gets created multiple times and then fails

### ISSUE THREAD

**Issue by ehassett** [hashicorp/terraform-provider-tfe#787]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
1.3.7
```

#### Terraform Configuration Files

```terraform
resource "tfe_variable_set" "hcp_packer" {
  count = length(var.hcp_packer_client_id) > 0 && length(var.hcp_packer_client_secret) > 0 ? 1 : 0

  name        = "hcp-packer-view-only"
  description = "Variable Set to access HCP Packer (View-only) for AMI usage."

  organization = local.organization
  global       = true
}
```

#### Debug Output

```plaintext
https://gist.github.com/ehassett/fe563c46f9100387b966a3c95bf70652
```

#### Expected Behavior

`tfe_variable_set` gets created once and then continues the apply.

#### Actual Behavior

1. `tfe_variable_set` gets created multiple times.
2. The run never recognizes that this gets created properly.
3. The apply fails with error:
```plaintext
 Name has already been taken
│ 
│   with tfe_variable_set.hcp_packer[0],
│   on main.tf line 59, in resource "tfe_variable_set" "hcp_packer":
│   59: resource "tfe_variable_set" "hcp_packer" {
│
```

#### Additional Context

N/A

**Comment by brandonc** [comment]
This is an interesting issue. It appears as though terraform retries after receiving a 504 error (this is normal) but also that the API endpoint completes the operation even though the gateway has timed out. I'm having trouble finding definitive proof of this as it is hard to recreate. I can say for certain that this is either a bug in go-httpretryable, which should not retry on 504, OR a bug in the platform, which should halt the operation when the client disconnects. I do know that our platform teams are working to decrease the latency of variable set endpoints, and I have brought this anecdote to the conversation.

In the meantime, you'll need to use `terraform import` to bring this resource into your state.
