### ISSUE TITLE
Unable to use data source: tfe_team with terraform cloud free version

### ISSUE THREAD

**Issue by pjolsen** [hashicorp/terraform-provider-tfe#817]
#### Terraform Cloud/Enterprise version
Terraform cloud

#### Terraform version

```
Terraform 1.3.9
```

#### Terraform Configuration Files

```
data "tfe_team" "test" {
  name         = "owners"
  organization = "<my-org-name>"
}
```

#### Debug Output
[gist](https://gist.github.com/pjolsen/2c5d529f42602af3b8e2e0de35ade3b6)

#### Expected Behavior
data finds the owners team and returns the object

#### Actual Behavior
errors stating that it is unable to find the team

#### Additional Context
Importing the resource using the team ID works fine and the name is "owners" within the imported state data.

**Comment by Uk1288** [comment]
Thank you for submitting this issue!

I was able to reproduce the errors using an [organization token](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#organization-api-tokens). I'd propose ensuring that the user or team token is used.

**Comment by ravindra-hp-jpmc** [comment]
I am also getting the same error please confirm the detailed solution
