### ISSUE TITLE
Support SAML settings

### ISSUE THREAD

**Issue by karvounis-form3** [hashicorp/terraform-provider-tfe#819]
#### Use-cases

We would like to manage SAML settings using the provider. However, this is not currently possible using this provider and it is advised to do so manually ([Okta integration tutorial](https://developer.hashicorp.com/terraform/tutorials/enterprise/enable-sso-saml-tfe-okta)). The Go client already [supports updating the SAML settings](https://github.com/hashicorp/go-tfe/blob/main/admin_setting_saml.go#L87-L100) ([TFE docs update SAML settings endpoint](https://developer.hashicorp.com/terraform/enterprise/api-docs/admin/settings#update-saml-settings)).

This is going to be helpful in order to manage SAML settings via Terraform code.

#### Proposal

- Create resource `tfe_admin_saml_settings` that [updates](https://developer.hashicorp.com/terraform/enterprise/api-docs/admin/settings#update-saml-settings) and [revokesIdpCert](https://developer.hashicorp.com/terraform/enterprise/api-docs/admin/settings#revoke-previous-saml-idp-certificate). 
- Create data source `tfe_admin_saml_settings` that [fetches SAML settings](https://developer.hashicorp.com/terraform/enterprise/api-docs/admin/settings#list-saml-settings)

**Comment by laurenolivia** [comment]
@karvounis-form3 thank you. We will look into this.

**Comment by laurenolivia** [comment]
Hi, @karvounis-form3. Thank you for following-up. We are aware of the feature request, however this isn't something we currently have prioritized.

**Comment by laurenolivia** [comment]
@karvounis-form3 What additional language in our documentation would have been more helpful? Happy to update our docs for additional clarity.

**Comment by uturunku1** [comment]
Hi @karvounis-form3! I am glad you mentioned the plugin docs tool. I tried it a few months ago https://github.com/hashicorp/terraform-provider-tfe/pull/863 but ended up not implementing. Some of the reasons are listed in the PR description.
I will take a look at your PR and if all looks good, I'll create a second PR (a copy of yours) with my GitHub permissions. You'll notice that your original PR cannot run our CI tests due to a permissions issue :(
As for your other PR for go-tfe, I may not be able to review it before the end of my engineering rotation, but I'll create a separate Jira ticket, so the next engineer in the rotation is aware that there is another separate issue/PR opened for go-tfe.

**Comment by tmatilai** [comment]
@karvounis-form3 Thank you so much for the work here! 🤗 
And thanks for HashiCorp for taking time to review and accept contributions! Hopefully we get the resource done and released, too. I can try to help if you need. At least to test.

I thought I had filed similar feature request, but seems that I only did it for the HCP provider. 🙂

**Comment by tmatilai** [comment]
Oh, and now I realize that the [API](https://developer.hashicorp.com/terraform/cloud-docs/api-docs) and [functionality](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/single-sign-on) are different on Terraform Cloud than TFE. In the web console there are separate ways to configure Okta or Azure providers, although they probably use the same generic SAML configurations internally.

The (undocumented?) API endpoint to fetch the configs seems to be `https://app.terraform.io/api/v2/organizations/<ORG_NAME>/saml-configurations`, and the ID has a generated suffix.

So I guess I still need to wait for HashiCorp to officially support SSO configurations in the TFC API. 

And maybe the `tfe_saml_settings` docs should state that it only works on TFE?

**Comment by tmatilai** [comment]
I guess most if not all other API endpoints are the same, but at least the admin endpoints are not exposed. And the SSO configurations are done on organization level, not for the whole tenant (which is managed by HashiCorp).
