### ISSUE TITLE
Get OAuth client by it's service provider not working

### ISSUE THREAD

**Issue by thomasjhenson** [hashicorp/terraform-provider-tfe#822]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
1.3.7
```

#### Terraform Configuration Files

```terraform
data "tfe_oauth_client" "client" {
  organization      = data.tfe_organization.org.name
  service_provider  = "github"
}
```

#### Debug Output

```plaintext
Error: Missing required argument
on ../../modules/workspace/main.tf line 1, in data "tfe_oauth_client" "client":
data "tfe_oauth_client" "client" {
The argument "oauth_client_id" is required, but no definition was found.

Error: Unsupported argument
on ../../modules/workspace/main.tf line 2, in data "tfe_oauth_client" "client":
  organization     = data.tfe_organization.org.name
An argument named "organization" is not expected here.

Error: Unsupported argument
on ../../modules/workspace/main.tf line 3, in data "tfe_oauth_client" "client":
  service_provider = "github"
An argument named "service_provider" is not expected here.
```

#### Expected Behavior

Successful read of OAuth client based on organisation and service provider.

#### Actual Behavior

Errors as above.

#### Additional Context

As per the [documentation](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/oauth_client#finding-an-oauth-client-by-its-service-provider:~:text=Finding%20an%20OAuth%20client%20by%20its%20service%20provider), I should be able to get Oatuh client by org and service provider. However, the error states oauth_client_id is required.

**Comment by nfagerlund** [comment]
Hello! I've investigated, and this seems to work 100% as intended in provider version 0.43.0 — I grabbed info for several oauth clients in one of my orgs on Terraform Cloud, referencing them by `service_provider` type for `bitbucket_hosted`, `gitlab_hosted`, and `github`, and also referencing by name (including for a name that included a bunch of spaces and parentheses in it). 

Based on your error message, it sounds a lot like you're trying to use this feature with an older version of the `tfe` provider — I went looking, and it appears [this was only added in 0.38.0](https://github.com/hashicorp/terraform-provider-tfe/commit/0ed823df8). Anything older than that will only accept the oauth client ID in the data source. 

Give it a try with the current version of the provider and see how that works. If it's still broken, please let us know!
