### ISSUE TITLE
manage_workspaces in tfe_team doesn't grant read access as of 0.43.0

### ISSUE THREAD

**Issue by reed-hanger** [hashicorp/terraform-provider-tfe#850]
I updated the tfe provider from 0.37.0 to 0.43.0 for a tfe_team recently:
```terraform
resource "tfe_team" "project_team" {
  provider     = tfe.org
  name         = "${var.project_name}_Team"
  organization = var.terraform_cloud_org
  organization_access {
    manage_workspaces = true
    manage_providers  = true
    manage_modules    = true
  }
}
```

This team primarily manages workspaces via Terraform. The only change when I updated the provider was to apply `view_workspaces = false` as that's a new config in organization_access in tfe 0.43.0. I figured manage_workspaces would trump read_workspaces, so I wouldn't need to explicitly set a permission for it, so I let it apply.
Then I ran a plan against several tfe_workspace resources using a token from that tfe_team. I was still able to run a plan with no errors using the modified tfe_team. However, the plans acted as though none of my existing Terraform workspaces existed despite logging the "Refreshing state..." lines for them with the correct workspace IDs. It wanted to create all of them, and if I removed one from my configuration, it didn't want to do anything to it.
When I explicitly set `read_workspaces = true` on the tfe_team, my plans started behaving normally again. I also didn't see this odd behavior at all when running the same plan as an org owner token.

#### Terraform version
1.4.4

#### Expected Behavior
Preferably, `manage_workspaces = true` would grant sufficient access. The Terraform Cloud GUI for team org access only allows "manage" OR "read" workspace access. It doesn't have an option to set both.
But even if it doesn't, I would have expected Terraform to throw an error that it doesn't have permission to view existing workspaces when it attempted to refresh the state of the tfe_workspace resources.

#### Actual Behavior
Terraform ran plans successfully (I did not want to attempt an apply) but wanted to create all existing tfe_workspace resources in the state as if they were new. Any existing tfe_workspace resources that I removed from the configuration did not show any planned changes in the plan.

#### Additional Context
Using Terraform Cloud with local applies.

This is our tfe_workspace definition:
```terraform
resource "tfe_workspace" "main" {
  for_each       = toset(var.environments)
  provider       = tfe.team
  name           = lower("${var.project_name}-iac_${each.key}")
  organization   = var.terraform_cloud_org
  execution_mode = "local"
  tag_names = [
    "repo:${lower(var.project_name)}-iac",
    "env:${each.key}",
    "lob:${var.line_of_business}"
  ]
  lifecycle {
    ignore_changes = [
      remote_state_consumer_ids,
      trigger_prefixes
    ]
  }
}
```

**Comment by evilensky** [comment]
>I would have expected Terraform to throw an error that it doesn't have permission to view existing workspaces 

As a TFC user, I am curious about this as well. I ran into similar issues with other API endpoints, for example, if one has the workspace permission of `manage_all_workspaces`, but not `read variables`, the TFC workspace variables API returns an empty `data[]` object.  In the case of the `tfe` provider, this results in continued attempts to plan and apply creating the variable.

Since this affects more than one endpoint, and more than one `tfe` provider resource, I ask if this is a back-end api design decision that needs to be revisited.
