### ISSUE TITLE
Error attempting to create workspace: `invalid attribute Repository doesn't exist or isn't accessible`

### ISSUE THREAD

**Issue by wchrisjohnson** [hashicorp/terraform-provider-tfe#854]
When we attempt to create a new workspace using Terraform, we get an error like this:
```
Error: 
Error creating workspace runtime-terraform-<name> for organization <org>: 
invalid attribute Repository doesn't exist or isn't accessible
```

Some background:
- We recently upgraded to the 0.43.0 version of the TFE Terraform provider to manage our TFC account. This was done to take advantage of the new Terraform Github app for VCS connections feature.
- Recently we updated all of our VCS related configs from an OIDC approach (`oauth_token_id `) to the Terraform GHA (`github_app_installation_id `). We are no longer using `oauth_token_id`.
- As a workaround, I can create a new workspace manually in the UI successfully and tweak the Terraform to match it. 
- We have enabled AllowListing for our GitHub org.
- We use Agents for our runs
- I have restarted the k8s pods we use for our agents - this appears to have no effect.
- This is working perfectly fine for updating existing workspaces; it seems to be affecting NEW workspace creations only. 
- All of the affected workspaces were VCS based and were connected to newly created GitHub repos.
- Our Terraform GitHub all is set to be able to access ALL REPOS, and not a selection of repos. We have a huge number of repos repos. 
- This is only happening in recent days since we updated to the 0.43.0 version of TFE terraform provider.
- It appears there are others experiencing this issue, but none of the issues reference a solution.
https://github.com/search?q=repo%3Ahashicorp%2Fterraform-provider-tfe+invalid+attribute+Repository+doesn%27t+exist+or+isn%27t+accessible&type=issues

My suspicion is that the client might be failing to find the repo in question due to the huge number of repos? Could this just be a paging issue (not paging) or a sheer volume issue?

We *could* enable select repos if that is suspected.

#### Terraform Cloud/Enterprise version

We are using TFC. 

#### Terraform version
```plaintext
1.2.8
```
#### Expected Behavior

It fails with the error noted above.

#### Actual Behavior

It worked before the most recent upgrade and change of VCS connection.

#### Additional Context

None that I can think of outside of what I've already outlined above.

**Comment by wchrisjohnson** [comment]
This ended up being a problem of my own making; shocking right?!

The TFC Workspace has a token associated with the TFE provider definition:
```
provider "tfe" {
  token = var.tfc_token
}
```

I had mistakenly set an Owner team token here. The way the new Terraform GitHub app works, the permissions of an individual user are passed thru when TFC talks to GitHub. This token needs to be associated with a user, any user, that has rights to interact with whatever GitHub repo(s) necessary for the Terraform in this repo to function.

Once I updated this token to a fresh personal token from my TFC account, it worked.

**Comment by olliefr** [comment]
Hi @wchrisjohnson! I've arrived at this page while troubleshooting a failing deployment and it helped me. So thank you for sharing this information. I have a question though. Given that your Terraform Cloud workspace now relies on a personal (User) token, what is going to happen if that user moves roles or leaves the org and their user account is deleted - would the previously generated token still continue to work?

**Comment by wchrisjohnson** [comment]
@olliefr There's no good answer to that question. The token will need to be rotated. Any user's token can be used so easy enough to fix but still not a great solution. 

While we've not yet chosen to pursue it, you might look into creating a GitHub "machine user" or bot account with the necessary permissions. Then create a corresponding TFC account to use to generate a token. Kludgy, for sure.

**Comment by naftulikay** [comment]
Triggered this now as well. I am managing `tfe_workspace` resources, I have the correct GitHub app installation id, and my existing workspaces function with "<org>/<repo>", which is the same for all workspaces I am managing, but I cannot create new workspaces. 

So, in short:

 1. If I create the workspace via the console, it works.
 2. If I create the workspace via Terraform, it fails.

Extremely odd, to say the least.

For whatever it's worth, I am doing the following in code:

```terraform
locals {
  github_org_name = "my-org"
  github_repo_name = "terraform"
  git_default_branch = "my-branch"
  tfcloud_org_name = "my-org"
}

variable workspaces {
    value = {
        "existing-workspace-name" = {
            "project" = "project-name"
        }
        "new-workspace-name" = {
            "project" = "project-name"
        }
    }
}

resource tfe_workspace default {
  for_each = var.workspaces

  name = each.key
  project_id = tfe_project.default[each.value["project"]].id
  organization = local.tfcloud_org_name
  working_directory = "workspaces/${each.key}"
  trigger_prefixes = distinct(["/workspaces/${each.key}"])

  vcs_repo {
    identifier = "${local.github_org_name}/${local.github_repo_name}"
    github_app_installation_id = var.tfcloud_github_app_installation_id
    branch = local.git_default_branch
  }

  force_delete = false
  allow_destroy_plan = false

  lifecycle {
    prevent_destroy = true
  }
}
```

Existing workspaces which I have imported work perfectly well and show no changes, and respond to changes appropriately. New workspaces fail with:

```text
 Error creating workspace new-workspace-name for organization my-org: invalid attribute Repository doesn't exist or isn't accessible
```

The repository does exist, is accessible, and is _the same repository_ that is used by other workspaces. It also seems not possible to delete the Terraform Cloud GitHub app installation, so things are just... broken. I may file a new issue for this.

**Comment by c4milo** [comment]
I'm running into this issue as well, are there any known workarounds?

**Comment by naftulikay** [comment]
I was able to get it working by installing Terraform Cloud as a custom GitHub OAuth application, rather than the normal GitHub app installation.

**Comment by nwalters512** [comment]
Using a User token instead of a Team or Organization token did the trick for me!
