### ISSUE TITLE
Typo in documentation for data source `tfe_organization.assessments_enforced`

### ISSUE THREAD

**Issue by sdrzazga-nsd** [hashicorp/terraform-provider-tfe#896]
Hi.

I found by accident that there was a typo in the description for data source `tfe_organization.assessments_enforced` .

https://github.com/hashicorp/terraform-provider-tfe/blob/29fcfd1364698e894bc01f7e49baa6bd660fce68/website/docs/d/organization.html.markdown?plain=1#L32

`thier` -> `their`

Please accept my PR (https://github.com/hashicorp/terraform-provider-tfe/pull/895) to fix the issue.
Thanks in advance.

**Comment by barrettclark** [comment]
The PR was merged.
