### ISSUE TITLE
tfe_workspace_run resource checks wait_for_run too late

### ISSUE THREAD

**Issue by lucymhdavies** [hashicorp/terraform-provider-tfe#908]
#### Terraform Cloud/Enterprise version

main

#### Terraform version

latest, doesn't matter.

#### Terraform Configuration Files

```terraform
resource "tfe_workspace_run" "trigger_workspaces" {

  # Kick off an apply, but don't wait for it
  apply {
    wait_for_run   = false # Fire and forget
    manual_confirm = false # N/A if wait_for_run is false, but parameter is required
  }

  # workspace_id = "foobar not actually relevant here"

}
```

#### Debug Output

I can provide it later if needed, but doesn't appear necessary in this case.

#### Expected Behavior

Expecting that `wait_for_run` should kick off the initial run, and then call it good. No need to wait around for the run to actually finish, just fire-and-forget.

#### Actual Behavior

`wait_for_run` is called much later in the function
https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/workspace_run_helpers.go#L146-L154

This means that it actually behaves as a "wait for apply".

In my example above, I'm setting `manual_confirm = false`, which is why the resource is trying to kick off the apply itself (and is sometimes successful, depending on whether we hit the https://github.com/hashicorp/terraform-provider-tfe/issues/898 issue).

#### Additional Context

Spin-off of https://github.com/hashicorp/terraform-provider-tfe/issues/898

Per @nfagerlund 's request...
> It might benefit from a grid of expected behavior for the combinations of attrs. :D

This means I get to bring out a truth table 😀
I'll get something written up in a bit.

**Comment by lucymhdavies** [comment]
I was originally gonna have separate tables for both Apply and Destroy...

I don't think that's needed, the logic is the same. As such, I shall refer to both as just "Apply" in the below.



| manual_confirm | retry | wait_for_run | Expected Behavior | Actual Behavior |
|----------------|-------|--------------|-------------------|-----------------|
| false          | false | false        | Fire-And-Forget. wait_for_run is false, therefore we create a Run, get its ID, and consider our `tfe_workspace_run` created. Whatever happens next, we don't care| TODO            |
| false          | false | true         | Apply-And-Wait. Let the run plan, then (if needed) confirm an apply. Wait until the Run has completed. If the final status is `tfe.RunApplied`, fantastic! If it's `tfe.RunErrored`, then we (maybe) try again | TODO            |
| false          | true  | false        | Fire-And-Forget, as above. `retry` ignored | TODO            |
| false          | true  | true         | Apply-And-Wait, as above. If the run fails, try again.    | TODO            |
| true           | false | false        | Fire-And-Forget, as above. `manual_confirm` ignored | TODO            |
| true           | false | true         | Plan-And-Wait. Same as Apply-And-Wait above, but wait for a human to confirm the apply.  | TODO            |
| true           | true  | false        | Fire-And-Forget, as above. Other arguments ignored. | TODO            |
| true           | true  | true         | Plan-And-Wait. If the run fails, try again. | TODO            |

**Comment by nfagerlund** [comment]
🤔 Something to consider: perhaps `manual_confirm` should mean something different if `wait_for_run = false`. 

Right now, we _always_ create runs with auto-apply false, so that the resource has full control over the run confirmation. And then `manual_confirm` is whether we sit and wait for the user to approve in UI, or hit confirm ourselves. 

But if we're told not to wait for the run at all, maybe we should create the run with `AutoApply: ! manual_confirm`. That would match my expectations as a user.

**Comment by lucymhdavies** [comment]
That's a good point. I think I agree with you on that. I'll update the table accordingly

**Comment by lucymhdavies** [comment]
To confirm... AutoApply only actually does something on a Run if the workspace is set up like this?

<img width="635" alt="image" src="https://github.com/hashicorp/terraform-provider-tfe/assets/1116529/397f4f94-88ce-4edc-83d3-f7354902deb9">


If the workspace is set up like this instead, then my understanding is that AutoApply is ignored by TFC

<img width="647" alt="image" src="https://github.com/hashicorp/terraform-provider-tfe/assets/1116529/3886fb27-53d7-4200-8c75-cb5d76acc6b5">

**Comment by lucymhdavies** [comment]
I think my Expected Behaviors in the truth table above are now good. Had to rework a few of them :)

**Comment by lucymhdavies** [comment]
I now also have Actual Behaviors listed. And good news, looks like it's going to be a simple fix.

**Comment by lucymhdavies** [comment]
Yep, confirmed that's how this works.

If AutoApply is true, then this overrides the workspace's Manual Apply Method.

<img width="821" alt="image" src="https://github.com/hashicorp/terraform-provider-tfe/assets/1116529/691fdfea-696b-45f4-83a1-917882ebde28">
<img width="645" alt="image" src="https://github.com/hashicorp/terraform-provider-tfe/assets/1116529/5e9ad635-ba3d-48a0-ab4f-216a8aa91649">


So `manual_confirm` needs to be optional in that case and, if ommited, then we do not include it in our API payload.

**Comment by nfagerlund** [comment]
Circling back to confirm that Yes, the "auto-apply TRUE on run overrides FALSE setting from workspace" thing is very much intentional. (It's for letting you do one-off auto-apply runs via the CLI, among other use cases.) Conversely, "auto-apply FALSE on run overrides TRUE setting from workspace" also works and is also intentional.

**Comment by lucymhdavies** [comment]
Yeah, it makes sense that it should work that way. Much more intuitive than how I thought it worked, tbh :)

**Comment by lucymhdavies** [comment]
Not gonna raise a PR just yet, but I _think_ this is the fix:
https://github.com/hashicorp/terraform-provider-tfe/commit/3cd6b51832e270e543bd2fb069667e3c2dceb8c7

**Comment by lucymhdavies** [comment]
I’m not actually going to bother with the “what if we made manual_confirm optional” thing I mentioned above.

tfe_workspace_run is already pretty advanced usage… and I can’t think of any situation where you’re using it and you don’t already know whether you want to manual_confirm or not.

and for situations where you don’t know, and want to use the workspace default… you can find out what the default is through the tfe_workspace data source.

**Comment by lucymhdavies** [comment]
Doing a quick functional test...

```
  apply {
    manual_confirm = true # Force manual confirm
    retry = false # Only try once
    wait_for_run = false # Fire and forget
  }
```

Apply...

```
tfe_workspace_run.trigger_workspaces["workspace-ages"]: Creating...
tfe_workspace_run.trigger_workspaces["nocode-aws-creds"]: Creating...
tfe_workspace_run.trigger_workspaces["nocode-azure-creds"]: Creating...
tfe_workspace_run.trigger_workspaces["nocode-aws-creds"]: Creation complete after 1s [id=run-BGTXSvkN5NxBPNUT]
tfe_workspace_run.trigger_workspaces["nocode-azure-creds"]: Creation complete after 1s [id=run-GQ8BVJNgWDWjXqs2]
tfe_workspace_run.trigger_workspaces["workspace-ages"]: Creation complete after 1s [id=run-6D4ehX7TXD5krmGj]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

which, in turn, kicked off a few runs which, in this case, were no-ops.



but with a few other workspaces, which _do_ have some plans...

```
tfe_workspace_run.trigger_workspaces["webserver-aws-dev"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-test"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-dev-network"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-dev"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-aws-prod"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-aws-test"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-prod"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-aws-prod"]: Creation complete after 2s [id=run-D5ftbJ9hLsqWgdP3]
tfe_workspace_run.trigger_workspaces["webserver-aws-test"]: Creation complete after 2s [id=run-rAKAtb1BSEFmJV6m]
tfe_workspace_run.trigger_workspaces["webserver-azure-test"]: Creation complete after 2s [id=run-QYqARTehtm2YftYt]
tfe_workspace_run.trigger_workspaces["webserver-aws-dev"]: Creation complete after 2s [id=run-XrVXsDNBQjnFza2N]
tfe_workspace_run.trigger_workspaces["webserver-azure-dev"]: Creation complete after 2s [id=run-JymupJ3Xd2bxkqkm]
tfe_workspace_run.trigger_workspaces["webserver-azure-dev-network"]: Creation complete after 3s [id=run-HwYxyJewq1Db4A4R]
tfe_workspace_run.trigger_workspaces["webserver-azure-prod"]: Creation complete after 3s [id=run-e1Ky4LPZcEhFqTUA]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.
```

(as expected)

Plans are run... and we're now waiting on human approval.

<img width="923" alt="image" src="https://github.com/hashicorp/terraform-provider-tfe/assets/1116529/dd4bcc8d-1a2b-4ea9-9898-7f61fa6f15dc">


So that's looking good.

**Comment by lucymhdavies** [comment]
And with

```
  apply {
    manual_confirm = false # go ahead and apply automatically
    retry = false # Only try once
    wait_for_run = false # Fire and forget
  }
```


```
tfe_workspace_run.trigger_workspaces["nocode-azure-creds"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-prod"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-aws-dev"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-dev-network"]: Creating...
tfe_workspace_run.trigger_workspaces["workspace-ages"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-aws-prod"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-dev"]: Creating...
tfe_workspace_run.trigger_workspaces["nocode-aws-creds"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-azure-test"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-aws-test"]: Creating...
tfe_workspace_run.trigger_workspaces["webserver-aws-dev"]: Creation complete after 1s [id=run-qqAf7Ph24pNJn4w6]
tfe_workspace_run.trigger_workspaces["webserver-aws-prod"]: Creation complete after 1s [id=run-5ojSDoM2c764aLZG]
tfe_workspace_run.trigger_workspaces["webserver-azure-test"]: Creation complete after 1s [id=run-6SFcGyZMpPdiT8Lp]
tfe_workspace_run.trigger_workspaces["webserver-azure-dev"]: Creation complete after 1s [id=run-XP2SKPVCMXr7rueA]
tfe_workspace_run.trigger_workspaces["nocode-aws-creds"]: Creation complete after 1s [id=run-3CNyxm5kjUcn5o7T]
tfe_workspace_run.trigger_workspaces["workspace-ages"]: Creation complete after 1s [id=run-CYUE5pb9hu2qn4D2]
tfe_workspace_run.trigger_workspaces["webserver-aws-test"]: Creation complete after 1s [id=run-VX16yhpVZMLrhXUX]
tfe_workspace_run.trigger_workspaces["webserver-azure-prod"]: Creation complete after 1s [id=run-7XBgseLZRF4kjuuH]
tfe_workspace_run.trigger_workspaces["nocode-azure-creds"]: Creation complete after 1s [id=run-d7BXbf5wDkLKjvFf]
tfe_workspace_run.trigger_workspaces["webserver-azure-dev-network"]: Creation complete after 1s [id=run-sMKd4QkoakkYovr2]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 10 added, 0 changed, 0 destroyed.
```

looking good too...

and the corresponding run does auto-apply as expected
(and as expected, it overrides the workspace's default setting)

<img width="638" alt="image" src="https://github.com/hashicorp/terraform-provider-tfe/assets/1116529/e7b818f4-a405-4e63-9952-cc4b9c726d86">
<img width="932" alt="image" src="https://github.com/hashicorp/terraform-provider-tfe/assets/1116529/d238b751-5d0b-4f49-a038-5b90f7cd43ea">



So functionally... I think this is all good :)


I've not run any of the tests yet, so I'll get a draft PR raised, and we'll see which (if any) fail.

I'll also have a think about some doc updates to better explain how these parameters work.

**Comment by lucymhdavies** [comment]
Fixed by https://github.com/hashicorp/terraform-provider-tfe/pull/917
