### ISSUE TITLE
tfe_registry_module not found for tfe_no_code_module

### ISSUE THREAD

**Issue by kevinawongw** [hashicorp/terraform-provider-tfe#914]
#### Terraform Cloud/Enterprise version

`Terraform Enterprise v202305-1`

#### Terraform version

```
Terraform v1.4.6

```

#### Terraform Configuration Files

```

resource "tfe_registry_module" "foobar" {
    vcs_repo {
        display_identifier = "..."
        identifier = "..."
        oauth_token_id = var.oauth_token_id
    }
}

resource "tfe_no_code_module" "foobar" {
    organization = "my-org"
    registry_module = tfe_registry_module.foobar.id
}

```

#### Debug Output

```
Error: Error creating no-code module for registry module <module-id>: resource not found
```

#### Expected Behavior

The module is added to the private module registry, and no-code is enabled for the module

#### Actual Behavior

The module was added and created, but no-code was not enabled because it was not able to find the resource.

#### Additional Context

I also tried adding `depends_on` to `tfe_no_code_module` to see if that would be the fix. Also tried manually adding my module to the registry first, grabbing the id, and directly setting `registry_module="mod-<id>"`. No luck for either of those with the same error produced.

**Comment by brandonc** [comment]
Thanks for the bug report. Are both the module and the no_code_module in the same organization? If you re-apply, do you get the same outcome?

You should not need a depends_on argument because it does the exact same thing as referencing the tfe_registry_module.foobar resource directly (as you've done) but manually putting the ID into the resource will probably help isolate the issue for us.

**Comment by kevinawongw** [comment]
Yes, the same org for both. I actually also tried removing `organization` from both resources and setting the organization in the provider to ensure the organization was the same for both but still saw the same error.
```
provider "tfe" {
  hostname = "my_hostname"
  token    = var.token
  organization = "my_org"
}
```

**Comment by brandonc** [comment]
@kevinawongw So I tried this in various ways using Terraform Cloud and it seemed to work as expected for both `module_provider` and `vcs_repo` modules. I suspect if there is a bug it could be affecting your version of Terraform Enterprise (or it could be an unaccounted detail of your specific org or module that I didn't capture). Can you contact your enterprise support channel for assistance? Or even try a minimal version of your config on Terraform Cloud (if possible) to confirm or disconfirm my suspicion. Here is a minimal config I tried that you can adapt to your usage:

```terraform
provider "tfe" {}

resource "tfe_organization" "foobar" {
    name  = "example-bcroft-no-code-modules"
    email = "your_email@hashicorp.com"
}

resource "tfe_oauth_client" "test-oauth-client" {
  organization     = tfe_organization.foobar.name
  api_url          = "https://api.github.com"
  http_url         = "https://github.com"
  oauth_token      = "XXXXXXXXXXXXXXXXXXXXXX"
  service_provider = "github"
}

resource "tfe_registry_module" "foobar" {
    organization    = tfe_organization.foobar.id
    name            = "test_module"

    vcs_repo {
        display_identifier = "brandonc/terraform-aws-simple-s3-cdn"
        identifier         = "brandonc/terraform-aws-simple-s3-cdn"
        oauth_token_id     = tfe_oauth_client.test-oauth-client.oauth_token_id
    }
}

resource "tfe_no_code_module" "foobar" {
    organization = tfe_organization.foobar.id
    registry_module = tfe_registry_module.foobar.id
}

```

**Comment by kevinawongw** [comment]
Yep- My current config pretty closely matches the minimal config you provided other than adding a hostname to the provider and explicitly defining the organization. but the same issues occur. I will also open a support ticket as suggested  :)

**Comment by brandonc** [comment]
Ohhh I see the problem. I believe no-code module creation is not available in your version of Terraform Enterprise yet. I'm basing this assumption on the fact that the API docs for this endpoint are [missing](https://developer.hashicorp.com/terraform/enterprise/api-docs) from Terraform Enterprise docs, but [present](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/no-code-provisioning) on the Terraform Cloud API docs

**Comment by kevinawongw** [comment]
Ohh gotcha. So is there currently any way of creating no-code modules for Terraform Enterprise? or is it just a matter of waiting until that's available
