### ISSUE TITLE
tfe_workspace_run triggered destroy assumes different role in child workspace

### ISSUE THREAD

**Issue by kashya2** [hashicorp/terraform-provider-tfe#989]
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```
1.5.2
```

#### Terraform Configuration Files

```
resource "tfe_workspace_run" "root_A" {
  workspace_id    = tfe_workspace.this.id

  apply {
    manual_confirm    = false
  }
  destroy { 
    manual_confirm = false
  }
}
```

#### Debug Output

```plaintext
w
```

#### Expected Behavior

The destroy trigger from the parent workspace should have made all the resource delete in child workspace

#### Actual Behavior

Child workspace fails while applying destroy operation with error (Access Denied)

#### Additional Context

NA

**Comment by brandonc** [comment]
@kashya2 Hello, and thanks for the error report. I need a little more clarity about your specific circumstances. Is the Access Denied error expected based on the the token that the provider has been configured with? Can you provide more details about the workspaces and their relevant permissions?

**Comment by barrettclark** [comment]
Closing automatically due to inactivity. If you still need help please reopen this issue.
